export var viStrings = {
  // survey templates
  survey: {
    edit: " Asc chỉnh sửa",
    externalHelpLink: "Xem và học cách tạo khảo sát",
    externalHelpLinkUrl:
      "https://www.youtube.com/channel/UCH2ru9okIcooNZfpIbyq4qQ?view_as=subscriber",
    dropQuestion: "Vui lòng thả một câu hỏi từ Hộp công cụ vào đây.",
    addLogicItem: "Tạo một quy tắc để tùy chỉnh luồng khảo sát.",
    copy: "Sao chép",
    duplicate: "Nhân bản",
    addToToolbox: "Thêm vào hộp công cụ",
    deletePanel: "Xóa Bảng",
    deleteQuestion: "Xóa Câu hỏi",
    convertTo: "Chuyển đổi thành",
    drag: "Kéo phần tử",
    license: "Quang Ngữ đã mò được đến chỗ này và sửa rồi nhé",
  },
  // Creator tabs
  tabs: {
    preview: "Xem trước",
    theme: "Chủ đề",
    translation: "Bản dịch",
    designer: "Thiết kế",
    json: "Trình chỉnh sửa JSON",
    logic: "Logic",
  },
  // Question types
  qt: {
    default: "Mặc định",
    checkbox: "Hộp kiểm",
    comment: "Văn bản dài",
    imagepicker: "Trình chọn hình ảnh",
    ranking: "Xếp hạng",
    image: "Hình ảnh",
    dropdown: "Danh sách thả xuống",
    tagbox: "Danh sách thả xuống đa lựa chọn",
    file: "Tải tệp lên",
    html: "HTML",
    matrix: "Ma trận lựa chọn đơn",
    matrixdropdown: "Ma trận lựa chọn đa",
    matrixdynamic: "Ma trận động",
    multipletext: "Nhiều hộp văn bản",
    panel: "Bảng",
    paneldynamic: "Bảng động",
    radiogroup: "Nhóm nút radio",
    rating: "Thang đánh giá",
    text: "Nhập dòng đơn",
    boolean: "Có/Không (Boolean)",
    expression: "Biểu thức (chỉ đọc)",
    signaturepad: "Bảng chữ ký",
    buttongroup: "Nhóm nút",
  },
  toolboxCategories: {
    general: "Tổng quan",
    choice: "Câu hỏi lựa chọn",
    text: "Câu hỏi nhập văn bản",
    containers: "Bộ chứa",
    matrix: "Câu hỏi ma trận",
    misc: "Khác",
  },
  // Strings in SurveyJS Creator
  ed: {
    defaultLocale: "Mặc định ({0})",
    survey: "Khảo sát",
    settings: "Cài đặt",
    settingsTooltip: "Mở cài đặt",
    surveySettings: "Cài đặt khảo sát",
    surveySettingsTooltip: "Cài đặt khảo sát",
    themeSettings: "Cài đặt chủ đề",
    themeSettingsTooltip: "Cài đặt chủ đề",
    creatorSettingTitle: "Cài đặt trình tạo",
    showPanel: "Hiển thị bảng",
    hidePanel: "Ẩn bảng",
    prevSelected: "Chọn trước đó",
    nextSelected: "Chọn tiếp theo",
    prevFocus: "Tập trung trước đó",
    nextFocus: "Tập trung tiếp theo",
    surveyTypeName: "Khảo sát",
    pageTypeName: "Trang",
    panelTypeName: "Bảng",
    questionTypeName: "Câu hỏi",
    columnTypeName: "Cột",
    addNewPage: "Thêm trang mới",
    moveRight: "Cuộn sang phải",
    moveLeft: "Cuộn sang trái",
    deletePage: "Xóa trang",
    editPage: "Chỉnh sửa trang",
    edit: "Chỉnh sửa",
    newPageName: "trang",
    newQuestionName: "câu hỏi",
    newPanelName: "bảng",
    newTextItemName: "văn bản",
    defaultV2Theme: "Mặc định",
    modernTheme: "Hiện đại",
    defaultTheme: "Mặc định (cũ)",
    testSurveyAgain: "Xem trước khảo sát lại",
    testSurveyWidth: "Chiều rộng khảo sát: ",
    navigateToMsg: "Bạn phải điều hướng đến",
    saveSurvey: "Lưu khảo sát",
    saveSurveyTooltip: "Lưu khảo sát",
    saveTheme: "Lưu chủ đề",
    saveThemeTooltip: "Lưu chủ đề",
    jsonoceErrors: "Ẩn lỗi",
    jsonShowErrors: "Hiển thị lỗi",
    undo: "Hoàn tác",
    redo: "Làm lại",
    undoTooltip: "Hoàn tác thay đổi cuối cùng",
    redoTooltip: "Làm lại thay đổi",
    expandTooltip: "Mở rộng",
    collapseTooltip: "Thu gọn",
    expandAllTooltip: "Mở rộng tất cả",
    collapseAllTooltip: "Thu gọn tất cả",
    zoomInTooltip: "Phóng to",
    zoom100Tooltip: "Phóng đến 100%",
    zoomOutTooltip: "Thu nhỏ",
    lockQuestionsTooltip: "Khóa trạng thái mở rộng/thu gọn cho câu hỏi",
    showMoreChoices: "Hiển thị thêm",
    showLessChoices: "Hiển thị ít hơn",
    copy: "Sao chép",
    cut: "Cắt",
    paste: "Dán",
    copyTooltip: "Sao chép lựa chọn vào bộ nhớ tạm",
    cutTooltip: "Cắt lựa chọn vào bộ nhớ tạm",
    pasteTooltip: "Dán từ bộ nhớ tạm",
    options: "Tùy chọn",
    generateValidJSON: "Tạo JSON hợp lệ",
    generateReadableJSON: "Tạo JSON dễ đọc",
    toolbox: "Hộp công cụ",
    "property-grid": "Thuộc tính",
    toolboxFilteredTextPlaceholder: "Nhập để tìm kiếm...",
    toolboxNoResultsFound: "Không tìm thấy kết quả",
    propertyGridFilteredTextPlaceholder: "Nhập để tìm kiếm...",
    propertyGridNoResultsFound: "Không tìm thấy kết quả",
    propertyGridPlaceholderTitle: "Bắt đầu cấu hình biểu mẫu của bạn",
    propertyGridPlaceholderDescription:
      "Nhấp vào bất kỳ biểu tượng danh mục nào để khám phá cài đặt khảo sát. Các cài đặt bổ sung sẽ khả dụng khi bạn thêm một phần tử khảo sát vào bề mặt thiết kế.",
    correctJSON: "Vui lòng sửa JSON.",
    surveyResults: "Kết quả khảo sát ",
    surveyResultsTable: "Dạng bảng",
    surveyResultsJson: "Dạng JSON",
    resultsTitle: "Tiêu đề câu hỏi",
    resultsName: "Tên câu hỏi",
    resultsValue: "Giá trị trả lời",
    resultsDisplayValue: "Giá trị hiển thị",
    modified: "Đã sửa đổi",
    saving: "Đang lưu",
    saved: "Đã lưu",
    propertyEditorError: "Lỗi",
    saveError: "Lỗi! Nội dung trình chỉnh sửa không được lưu.",
    translationPropertyGridTitle: "Cài đặt ngôn ngữ",
    themePropertyGridTitle: "Cài đặt chủ đề",
    addLanguageTooltip: "Thêm ngôn ngữ",
    translationLanguages: "Ngôn ngữ",
    translationDeleteLanguage:
      "Bạn có chắc chắn muốn xóa tất cả chuỗi cho ngôn ngữ này không?",
    translationAddLanguage: "Chọn ngôn ngữ để dịch",
    translationShowAllStrings: "Tất cả chuỗi",
    translationShowUsedStringsOnly: "Chỉ chuỗi đã sử dụng",
    translationShowAllPages: "Tất cả trang",
    translationNoStrings: "Không có chuỗi để dịch. Vui lòng thay đổi bộ lọc.",
    translationExportToSCVButton: "Xuất ra CSV",
    translationImportFromSCVButton: "Nhập từ CSV",
    translateUsigAI: "Tự động dịch tất cả",
    translateUsigAIFrom: "Dịch từ: ",
    translationDialogTitle: "Chuỗi chưa được dịch",
    translationMergeLocaleWithDefault: "Hợp nhất {0} với ngôn ngữ mặc định",
    translationPlaceHolder: "Bản dịch...",
    translationSource: "Nguồn: ",
    translationTarget: "Mục tiêu: ",
    translationYouTubeNotSupported: "Liên kết YouTube không được hỗ trợ.",
    themeExportButton: "Xuất",
    themeImportButton: "Nhập",
    surveyJsonExportButton: "Xuất",
    surveyJsonImportButton: "Nhập",
    surveyJsonCopyButton: "Sao chép vào bộ nhớ tạm",
    themeResetButton: "Đặt lại cài đặt chủ đề về mặc định",
    themeResetConfirmation:
      "Bạn có thực sự muốn đặt lại chủ đề không? Tất cả tùy chỉnh của bạn sẽ bị mất.",
    themeResetConfirmationOk: "Có, đặt lại chủ đề",
    bold: "Đậm",
    italic: "Nghiêng",
    underline: "Gạch chân",
    addNewQuestion: "Thêm câu hỏi",
    selectPage: "Chọn trang...",
    carryForwardChoicesCopied: "Các lựa chọn được sao chép từ",
    choicesLoadedFromWebText: "Các lựa chọn được tải từ dịch vụ web.",
    choicesLoadedFromWebLinkText: "Đi đến cài đặt",
    choicesLoadedFromWebPreviewTitle: "Xem trước các tùy chọn lựa chọn đã tải",
    htmlPlaceHolder: "Nội dung HTML sẽ ở đây.",
    panelPlaceHolder: "Thả một câu hỏi từ hộp công cụ vào đây.",
    surveyPlaceHolder:
      "Khảo sát trống. Kéo một phần tử từ hộp công cụ hoặc nhấp vào nút bên dưới.",
    pagePlaceHolder:
      "Trang trống. Kéo một phần tử từ hộp công cụ hoặc nhấp vào nút bên dưới.",
    imagePlaceHolder:
      "Kéo và thả hình ảnh vào đây hoặc nhấp vào nút bên dưới và chọn hình ảnh để tải lên",
    surveyPlaceHolderMobile:
      'Nhấp vào nút "Thêm câu hỏi" bên dưới để bắt đầu tạo biểu mẫu của bạn.',
    surveyPlaceholderTitle: "Biểu mẫu của bạn trống",
    surveyPlaceholderTitleMobile: "Biểu mẫu của bạn trống",
    surveyPlaceholderDescription:
      "Kéo một phần tử từ hộp công cụ hoặc nhấp vào nút bên dưới.",
    surveyPlaceholderDescriptionMobile:
      "Kéo một phần tử từ hộp công cụ hoặc nhấp vào nút bên dưới.",
    previewPlaceholderTitle: "Không có xem trước",
    previewPlaceholderTitleMobile: "Không có xem trước",
    previewPlaceholderDescription:
      "Khảo sát không chứa bất kỳ phần tử nào hiển thị.",
    previewPlaceholderDescriptionMobile:
      "Khảo sát không chứa bất kỳ phần tử nào hiển thị.",
    translationsPlaceholderTitle: "Không có chuỗi để dịch",
    translationsPlaceholderTitleMobile: "Không có chuỗi để dịch",
    translationsPlaceholderDescription:
      "Thêm phần tử vào biểu mẫu của bạn hoặc thay đổi bộ lọc chuỗi trong thanh công cụ.",
    translationsPlaceholderDescriptionMobile:
      "Thêm phần tử vào biểu mẫu của bạn hoặc thay đổi bộ lọc chuỗi trong thanh công cụ.",
    pagePlaceHolderMobile:
      'Nhấp vào nút "Thêm câu hỏi" bên dưới để thêm một phần tử mới vào trang.',
    panelPlaceHolderMobile:
      'Nhấp vào nút "Thêm câu hỏi" bên dưới để thêm một phần tử mới vào bảng.',
    imagePlaceHolderMobile: "Nhấp vào nút bên dưới và chọn hình ảnh để tải lên",
    imageChooseImage: "Chọn hình ảnh",
    addNewTypeQuestion: "Thêm {0}", //{0} is localizable question type
    chooseLogoPlaceholder: "[LOGO]",
    choices_Item: "Mục ",
    selectFile: "Chọn tệp",
    removeFile: "Xóa tệp",
    lg: {
      addNewItem: "Thêm quy tắc mới",
      empty_tab: "Tạo một quy tắc để tùy chỉnh luồng khảo sát.",
      logicPlaceholderTitle: "Không có quy tắc logic",
      logicPlaceholderTitleMobile: "Không có quy tắc logic",
      logicPlaceholderDescription:
        "Tạo một quy tắc để tùy chỉnh luồng khảo sát.",
      logicPlaceholderDescriptionMobile:
        "Tạo một quy tắc để tùy chỉnh luồng khảo sát.",
      page_visibilityName: "Hiển thị/ẩn trang",
      page_enableName: "Bật/tắt trang",
      page_requireName: "Yêu cầu trang",
      panel_visibilityName: "Hiển thị/ẩn bảng",
      panel_enableName: "Bật/tắt bảng",
      panel_requireName: "Yêu cầu bảng",
      question_visibilityName: "Hiển thị/ẩn câu hỏi",
      question_enableName: "Bật/tắt câu hỏi",
      question_requireName: "Yêu cầu câu hỏi",
      question_resetValueName: "Đặt lại giá trị câu hỏi",
      question_setValueName: "Đặt giá trị câu hỏi",
      column_visibilityName: "Hiển thị/ẩn cột",
      column_enableName: "Bật/tắt cột",
      column_requireName: "Yêu cầu cột",
      column_resetValueName: "Đặt lại giá trị cột",
      column_setValueName: "Đặt giá trị cột",
      trigger_completeName: "Hoàn thành khảo sát",
      trigger_setvalueName: "Đặt câu trả lời",
      trigger_copyvalueName: "Sao chép câu trả lời",
      trigger_skipName: "Bỏ qua đến câu hỏi",
      trigger_runExpressionName: "Chạy biểu thức",
      completedHtmlOnConditionName: 'Đặt đánh dấu trang "Cảm ơn"',
      page_visibilityDescription:
        "Hiển thị trang khi biểu thức logic trả về true. Nếu không, giữ trang ẩn.",
      panel_visibilityDescription:
        "Hiển thị bảng khi biểu thức logic trả về true. Nếu không, giữ bảng ẩn.",
      panel_enableDescription:
        "Bật bảng và tất cả phần tử bên trong khi biểu thức logic trả về true. Nếu không, giữ chúng bị tắt.",
      question_visibilityDescription:
        "Hiển thị câu hỏi khi biểu thức logic trả về true. Nếu không, giữ câu hỏi ẩn.",
      question_enableDescription:
        "Bật câu hỏi khi biểu thức logic trả về true. Nếu không, giữ câu hỏi bị tắt.",
      question_requireDescription:
        "Câu hỏi trở thành bắt buộc khi biểu thức logic trả về true.",
      trigger_completeDescription:
        'Khi biểu thức logic trả về true, khảo sát kết thúc, và người trả lời thấy trang "Cảm ơn".',
      trigger_setvalueDescription:
        "Khi giá trị câu hỏi được sử dụng trong biểu thức logic thay đổi và biểu thức trả về true, giá trị được chỉ định sẽ được gán cho câu hỏi đã chọn.",
      trigger_copyvalueDescription:
        "Khi giá trị câu hỏi được sử dụng trong biểu thức logic thay đổi và biểu thức trả về true, giá trị của câu hỏi đã chọn được sao chép sang câu hỏi khác.",
      trigger_skipDescription:
        "Khi biểu thức logic trả về true, khảo sát sẽ tập trung/chuyển đến câu hỏi đã chọn.",
      trigger_runExpressionDescription:
        "Khi biểu thức logic trả về true, khảo sát sẽ đánh giá một biểu thức khác. Tùy chọn, kết quả của biểu thức này có thể được gán làm giá trị cho câu hỏi đã chọn",
      completedHtmlOnConditionDescription:
        'Nếu biểu thức logic trả về true, trang "Cảm ơn" sẽ hiển thị nội dung được chỉ định.',
      itemExpressionText: "Khi biểu thức: '{0}' trả về true", //{0} - the expression
      itemEmptyExpressionText: "Quy tắc mới",
      page_visibilityText: "hiển thị trang {0}", //{0} page name
      panel_visibilityText: "hiển thị bảng {0}", //{0} panel name
      panel_enableText: "bật bảng {0}", //{0} panel name
      question_visibilityText: "hiển thị câu hỏi {0}", //{0} question name
      question_enableText: "bật câu hỏi {0}", //{0} question name
      question_requireText: "yêu cầu câu hỏi {0}", //{0} question name
      question_resetValueText: "đặt lại giá trị cho câu hỏi: {0}", //{0} question name
      question_setValueText: "gán giá trị: {1} cho câu hỏi: {0}", //{0} question name tới {1} setValueExpression
      column_visibilityText: "hiển thị cột {0} của câu hỏi {1}", //{0} column name, {1} question name
      column_enableText: "bật cột {0} của câu hỏi {1}", //{0} column name, {1} question name
      column_requireText: "yêu cầu cột {0} của câu hỏi {1}", //{0} column name, {1} question name
      column_resetValueText: "đặt lại giá trị ô cho cột: {0}", //{0} column name
      column_setValueText: "gán giá trị ô: {1} cho cột: {0}", //{0} column name tới {1} setValueExpression
      setValueExpressionPlaceholder:
        "Một biểu thức mà kết quả của nó sẽ được gán cho câu hỏi mục tiêu.",
      trigger_completeText: "khảo sát hoàn thành",
      trigger_setvalueText: "đặt vào câu hỏi: {0} giá trị {1}", //{0} question name, {1} setValue
      trigger_setvalueEmptyText: "xóa giá trị câu hỏi: {0}", //{0} question name
      trigger_copyvalueText: "sao chép vào câu hỏi: {0} giá trị từ câu hỏi {1}", //{0} tới {1} question names
      trigger_skipText: "khảo sát bỏ qua đến câu hỏi {0}", //{0} question name
      trigger_runExpressionText1: "chạy biểu thức: '{0}'", //{0} the expression
      trigger_runExpressionText2: " và đặt kết quả vào câu hỏi: {0}", //{0} question name
      completedHtmlOnConditionText:
        'hiển thị văn bản tùy chỉnh cho trang "Cảm ơn".',
      showAllQuestions: "Tất cả câu hỏi",
      showAllActionTypes: "Tất cả loại hành động",
      conditions: "Điều kiện",
      actions: "Hành động",
      expressionEditorTitle: "Xác định điều kiện",
      actionsEditorTitle: "Xác định hành động",
      deleteAction: "Xóa hành động",
      addNewAction: "Thêm hành động",
      selectedActionCaption: "Chọn hành động...",
      expressionInvalid:
        "Biểu thức logic trống hoặc không hợp lệ. Vui lòng sửa lại.",
      noActionError: "Vui lòng thêm ít nhất một hành động.",
      actionInvalid: "Vui lòng sửa các vấn đề trong hành động của bạn.",
      uncompletedRule_title: "Quy tắc logic chưa hoàn thành",
      uncompletedRule_text:
        "Bạn chưa hoàn thành một số quy tắc logic. Nếu bạn rời khỏi tab bây giờ, các thay đổi sẽ bị mất. Bạn có vẫn muốn rời khỏi tab mà không hoàn thành các thay đổi không?",
      uncompletedRule_apply: "Có",
      uncompletedRule_cancel: "Không, tôi muốn hoàn thành các quy tắc",
    },
  },
  // Property Editors
  pe: {
    panel: {
      name: "Tên bảng",
      title: "Tiêu đề bảng",
      description: "Mô tả bảng",
      visibleIf: "Hiển thị bảng nếu",
      requiredIf: "Yêu cầu bảng nếu",
      questionOrder: "Thứ tự câu hỏi trong bảng",
      page: "Di chuyển bảng đến trang",
      startWithNewLine: "Hiển thị bảng trên dòng mới",
      state: "Trạng thái thu gọn bảng",
      width: "Chiều rộng bảng nội tuyến",
      minWidth: "Chiều rộng tối thiểu của bảng",
      maxWidth: "Chiều rộng tối đa của bảng",
      showNumber: "Đánh số bảng này",
    },
    panellayoutcolumn: {
      effectiveWidth: "Chiều rộng hiệu quả, %",
      questionTitleWidth: "Chiều rộng tiêu đề câu hỏi, px",
    },
    paneldynamic: {
      name: "Tên bảng",
      title: "Tiêu đề bảng",
      description: "Mô tả bảng",
      visibleIf: "Hiển thị bảng nếu",
      requiredIf: "Yêu cầu bảng nếu",
      page: "Di chuyển bảng đến trang",
      startWithNewLine: "Hiển thị bảng trên dòng mới",
      state: "Trạng thái thu gọn bảng",
      width: "Chiều rộng bảng nội tuyến",
      minWidth: "Chiều rộng tối thiểu của bảng",
      maxWidth: "Chiều rộng tối đa của bảng",
      confirmDelete: "Xác nhận xóa bảng",
      templateDescription: "Mẫu mô tả bảng",
      templateTitle: "Mẫu tiêu đề bảng",
      noEntriesText: "Văn bản bảng trống",
      templateTabTitle: "Mẫu tiêu đề tab",
      tabTitlePlaceholder: "Trình giữ chỗ tiêu đề tab",
      templateVisibleIf: "Hiển thị bảng riêng lẻ nếu",
      showNumber: "Đánh số bảng",
      titleLocation: "Căn chỉnh tiêu đề bảng",
      descriptionLocation: "Căn chỉnh mô tả bảng",
      templateQuestionTitleLocation: "Căn chỉnh tiêu đề câu hỏi",
      templateQuestionTitleWidth: "Chiều rộng tiêu đề câu hỏi",
      templateErrorLocation: "Căn chỉnh thông báo lỗi",
      newPanelPosition: "Vị trí bảng mới",
      showRangeInProgress: "Hiển thị thanh tiến trình",
      keyName: "Ngăn chặn câu trả lời trùng lặp trong câu hỏi sau",
    },
    question: {
      name: "Tên câu hỏi",
      title: "Tiêu đề câu hỏi",
      description: "Mô tả câu hỏi",
      visibleIf: "Hiển thị câu hỏi nếu",
      requiredIf: "Yêu cầu câu hỏi nếu",
      page: "Di chuyển câu hỏi đến trang",
      state: "Trạng thái thu gọn hộp câu hỏi",
      showNumber: "Đánh số câu hỏi này",
      titleLocation: "Căn chỉnh tiêu đề câu hỏi",
      descriptionLocation: "Căn chỉnh mô tả câu hỏi",
      errorLocation: "Căn chỉnh thông báo lỗi",
      indent: "Tăng khoảng cách thụt lề bên trong",
      width: "Chiều rộng câu hỏi nội tuyến",
      minWidth: "Chiều rộng tối thiểu của câu hỏi",
      maxWidth: "Chiều rộng tối đa của câu hỏi",
      textUpdateMode: "Cập nhật giá trị trường nhập",
    },
    signaturepad: {
      signatureWidth: "Chiều rộng khu vực chữ ký",
      signatureHeight: "Chiều cao khu vực chữ ký",
      signatureAutoScaleEnabled: "Tự động điều chỉnh tỷ lệ khu vực chữ ký",
      showPlaceholder: "Hiển thị trình giữ chỗ trong khu vực chữ ký",
      placeholder: "Văn bản trình giữ chỗ",
      placeholderReadOnly:
        "Văn bản trình giữ chỗ trong chế độ chỉ đọc hoặc xem trước",
      allowClear: "Hiển thị nút Xóa trong khu vực chữ ký",
      penMinWidth: "Chiều rộng nét tối thiểu",
      penMaxWidth: "Chiều rộng nét tối đa",
      penColor: "Màu nét",
    },
    comment: {
      rows: "Chiều cao trường nhập (theo dòng)",
    },
    showQuestionNumbers: "Đánh số câu hỏi",
    questionStartIndex: "Loại đánh số câu hỏi",
    expression: {
      name: "Tên biểu thức",
      title: "Tiêu đề biểu thức",
      description: "Mô tả biểu thức",
      expression: "Biểu thức",
    },
    trigger: {
      expression: "Biểu thức",
    },
    calculatedvalue: {
      expression: "Biểu thức",
    },
    // survey templates
    survey: {
      title: "Tiêu đề khảo sát",
      description: "Mô tả khảo sát",
      readOnly: "Đặt khảo sát ở chế độ chỉ đọc",
    },
    page: {
      name: "Tên trang",
      title: "Tiêu đề trang",
      description: "Mô tả trang",
      visibleIf: "Hiển thị trang nếu",
      requiredIf: "Yêu cầu trang nếu",
      timeLimit: "Giới hạn thời gian để hoàn thành trang",
      questionOrder: "Thứ tự câu hỏi trên trang",
    },
    matrixdropdowncolumn: {
      name: "Tên cột",
      title: "Tiêu đề cột",
      isUnique: "Ngăn chặn câu trả lời trùng lặp",
      width: "Chiều rộng cột",
      minWidth: "Chiều rộng tối thiểu của cột",
      rows: "Chiều cao trường nhập (theo dòng)",
      visibleIf: "Hiển thị cột nếu",
      requiredIf: "Yêu cầu cột nếu",
      showInMultipleColumns: "Mỗi tùy chọn trong một cột riêng",
    },
    multipletextitem: {
      name: "Tên",
      title: "Tiêu đề",
    },
    masksettings: {
      saveMaskedValue: "Lưu giá trị đã che trong kết quả khảo sát",
    },
    patternmask: {
      pattern: "Mẫu giá trị",
    },
    datetimemask: {
      min: "Giá trị tối thiểu",
      max: "Giá trị tối đa",
    },
    numericmask: {
      allowNegativeValues: "Cho phép giá trị âm",
      thousandsSeparator: "Dấu phân cách hàng nghìn",
      decimalSeparator: "Dấu phân cách thập phân",
      precision: "Độ chính xác giá trị",
      min: "Giá trị tối thiểu",
      max: "Giá trị tối đa",
    },
    currencymask: {
      prefix: "Tiền tố tiền tệ",
      suffix: "Hậu tố tiền tệ",
    },
    imageHeight: "Chiều cao khu vực hiển thị",
    imageWidth: "Chiều rộng khu vực hiển thị",
    valueName: "Định danh kết nối",
    defaultDisplayValue: "Giá trị hiển thị mặc định cho văn bản động",
    rateDescriptionLocation: "Căn chỉnh nhãn",
    size: "Chiều rộng trường nhập (theo ký tự)",
    cellErrorLocation: "Căn chỉnh thông báo lỗi ô",
    enabled: "Bật",
    disabled: "Tắt",
    inherit: "Kế thừa",
    apply: "Áp dụng",
    ok: "OK",
    save: "Lưu",
    clear: "Xóa",
    saveTooltip: "Lưu",
    cancel: "Hủy",
    set: "Đặt",
    reset: "Đặt lại",
    change: "Thay đổi",
    refresh: "Làm mới",
    close: "Đóng",
    delete: "Xóa",
    add: "Thêm",
    addNew: "Thêm mới",
    addItem: "Nhấp để thêm một mục...",
    removeItem: "Nhấp để xóa mục...",
    dragItem: "Kéo mục",
    addOther: "Khác",
    addSelectAll: "Chọn tất cả",
    addNone: "Không có",
    removeAll: "Xóa tất cả",
    edit: "Chỉnh sửa",
    back: "Quay lại mà không lưu",
    backTooltip: "Quay lại mà không lưu",
    saveAndBack: "Lưu và quay lại",
    saveAndBackTooltip: "Lưu và quay lại",
    doneEditing: "Hoàn tất",
    editChoices: "Chỉnh sửa lựa chọn",
    showChoices: "Hiển thị lựa chọn",
    move: "Di chuyển",
    empty: "<trống>",
    emptyValue: "Giá trị trống",
    fastEntry: "Nhập thủ công",
    fastEntryNonUniqueError: "Giá trị '{0}' không duy nhất",
    fastEntryChoicesCountError: "Vui lòng giới hạn số mục từ {0} đến {1}",
    fastEntryChoicesMinCountError: "Vui lòng nhập ít nhất {0} mục",
    fastEntryPlaceholder:
      "Nhập danh sách các tùy chọn lựa chọn và ID của chúng theo định dạng sau:\n\nid|tùy chọn\n\nID của tùy chọn lựa chọn không hiển thị với người trả lời và có thể được sử dụng trong các quy tắc điều kiện.",
    formEntry: "Nhập biểu mẫu",
    testService: "Kiểm tra dịch vụ",
    itemSelectorEmpty: "Vui lòng chọn phần tử",
    conditionActionEmpty: "Vui lòng chọn hành động",
    conditionSelectQuestion: "Chọn câu hỏi...",
    conditionSelectPage: "Chọn trang...",
    conditionSelectPanel: "Chọn bảng...",
    conditionValueQuestionTitle: "Vui lòng nhập/chọn giá trị",
    aceEditorHelp: "Nhấn ctrl+space để nhận gợi ý hoàn thành biểu thức",
    aceEditorRowTitle: "Dòng hiện tại",
    aceEditorPanelTitle: "Bảng hiện tại",
    showMore: "Để biết thêm chi tiết, vui lòng xem tài liệu",
    assistantTitle: "Câu hỏi có sẵn",
    cellsEmptyRowsColumns: "Phải có ít nhất một cột hoặc dòng",
    showPreviewBeforeComplete: "Xem lại trước khi gửi",
    overridingPropertyPrefix: "Được bật bởi điều kiện",
    resetToDefaultCaption: "Đặt lại",
    propertyIsEmpty: "Vui lòng nhập giá trị",
    propertyIsNoUnique: "Vui lòng nhập giá trị duy nhất",
    propertyNameIsNotUnique: "Vui lòng nhập tên duy nhất",
    propertyNameIsIncorrect:
      'Không sử dụng các từ khóa: "item", "choice", "panel", "row".',
    listIsEmpty: "Bạn chưa có mục nào",
    "listIsEmpty@choices": "Bạn chưa có lựa chọn nào",
    "listIsEmpty@columns": "Bạn chưa có cột nào",
    "listIsEmpty@gridLayoutColumns": "Bạn chưa có cột bố cục lưới nào",
    "listIsEmpty@rows": "Bạn chưa có dòng nào",
    "listIsEmpty@validators": "Bạn chưa có quy tắc xác thực nào",
    "listIsEmpty@calculatedValues": "Bạn chưa có biến tùy chỉnh nào",
    "listIsEmpty@triggers": "Bạn chưa có trình kích hoạt nào",
    "listIsEmpty@navigateToUrlOnCondition": "Bạn chưa có liên kết nào",
    "listIsEmpty@pages": "Bạn chưa có trang nào",
    "addNew@choices": "Thêm lựa chọn mới",
    "addNew@columns": "Thêm cột mới",
    "addNew@rows": "Thêm dòng mới",
    "addNew@validators": "Thêm quy tắc mới",
    "addNew@calculatedValues": "Thêm biến mới",
    "addNew@triggers": "Thêm trình kích hoạt mới",
    "addNew@navigateToUrlOnCondition": "Thêm URL mới",
    "addNew@pages": "Thêm trang mới",
    expressionIsEmpty: "Biểu thức trống",
    value: "Giá trị",
    text: "Văn bản",
    rowid: "ID dòng",
    imageLink: "URL tệp hình ảnh hoặc video",
    columnEdit: "Chỉnh sửa cột: {0}",
    itemEdit: "Chỉnh sửa mục: {0}",
    url: "URL",
    path: "Đường dẫn đến dữ liệu",
    choicesbyurl: {
      url: "URL dịch vụ web",
      valueName: "Lấy giá trị để lưu từ thuộc tính sau",
    },
    titleName: "Lấy giá trị để hiển thị từ thuộc tính sau",
    imageLinkName: "Lấy URL tệp từ thuộc tính sau",
    allowEmptyResponse: "Chấp nhận phản hồi trống",
    titlePlaceholder: "Tiêu đề",
    surveyTitlePlaceholder: "Tiêu đề khảo sát",
    pageTitlePlaceholder: "Trang {num}",
    startPageTitlePlaceholder: "Trang bắt đầu",
    descriptionPlaceholder: "Mô tả",
    surveyDescriptionPlaceholder: "Mô tả",
    pageDescriptionPlaceholder: "Mô tả",
    textWrapEnabled: "Gói các lựa chọn",
    showOtherItem: 'Bật tùy chọn "Khác"',
    otherText: 'Đổi tên tùy chọn "Khác"',
    showNoneItem: 'Bật tùy chọn "Không có"',
    showRefuseItem: 'Bật tùy chọn "Từ chối trả lời"',
    showDontKnowItem: 'Bật tùy chọn "Không biết"',
    noneText: 'Đổi tên tùy chọn "Không có"',
    showSelectAllItem: 'Bật tùy chọn "Chọn tất cả"',
    selectAllText: 'Đổi tên tùy chọn "Chọn tất cả"',
    choicesMin: "Giá trị tối thiểu cho các mục tự động tạo",
    choicesMax: "Giá trị tối đa cho các mục tự động tạo",
    choicesStep: "Giá trị bước cho các mục tự động tạo",
    name: "Tên",
    title: "Tiêu đề",
    cellType: "Loại ô nhập",
    colCount: "Số cột",
    choicesOrder: "Thứ tự lựa chọn",
    allowCustomChoices: "Cho phép lựa chọn tùy chỉnh",
    visible: "Hiển thị",
    isRequired: "Bắt buộc",
    markRequired: "Đánh dấu là bắt buộc",
    removeRequiredMark: "Xóa dấu bắt buộc",
    eachRowRequired: "Yêu cầu câu trả lời trong mỗi dòng",
    eachRowUnique: "Ngăn chặn câu trả lời trùng lặp trong các dòng",
    requiredErrorText: "Thông báo lỗi cho câu hỏi bắt buộc",
    startWithNewLine: "Hiển thị câu hỏi trên dòng mới",
    rows: "Dòng",
    cols: "Cột",
    placeholder: "Văn bản trình giữ chỗ trong trường nhập",
    showPreview: "Hiển thị khu vực xem trước",
    storeDataAsText: "Lưu nội dung tệp trong kết quả JSON dưới dạng văn bản",
    maxSize: "Kích thước tệp tối đa (theo byte)",
    rowCount: "Số dòng",
    columnLayout: "Bố cục cột",
    addRowButtonLocation: 'Căn chỉnh nút "Thêm dòng"',
    transposeData: "Chuyển dòng thành cột",
    addRowText: 'Văn bản nút "Thêm dòng"',
    removeRowText: 'Văn bản nút "Xóa dòng"',
    singleInputTitleTemplate: "Mẫu tiêu đề trường nhập",
    rateMin: "Giá trị đánh giá tối thiểu",
    rateMax: "Giá trị đánh giá tối đa",
    rateStep: "Giá trị bước",
    minRateDescription: "Nhãn giá trị tối thiểu",
    maxRateDescription: "Nhãn giá trị tối đa",
    inputType: "Loại nhập",
    optionsCaption: "Trình giữ chỗ tùy chọn",
    defaultValue: "Câu trả lời mặc định",
    cellsDefaultRow: "Văn bản mặc định",
    surveyEditorTitle: "Chỉnh sửa cài đặt khảo sát",
    qEditorTitle: "Chỉnh sửa: {0}",
    maxLength: "Giới hạn ký tự tối đa",
    buildExpression: "Xây dựng",
    editExpression: "Chỉnh sửa",
    and: "và",
    or: "hoặc",
    remove: "Xóa",
    addCondition: "Thêm điều kiện",
    emptyLogicPopupMessage: "Chọn một câu hỏi để bắt đầu cấu hình điều kiện.",
    if: "Nếu",
    then: "thì",
    setToName: "Câu hỏi mục tiêu",
    fromName: "Câu hỏi để sao chép câu trả lời từ",
    gotoName: "Câu hỏi để bỏ qua đến",
    ruleIsNotSet: "Quy tắc không chính xác",
    includeIntoResult: "Thêm vào kết quả khảo sát",
    showTitle: "Hiển thị tiêu đề và mô tả",
    expandCollapseTitle: "Mở rộng/thu gọn tiêu đề",
    locale: "Chọn ngôn ngữ khảo sát",
    simulator: "Chọn loại thiết bị",
    landscapeOrientation: "Chuyển sang hướng ngang",
    portraitOrientation: "Chuyển sang hướng dọc",
    clearInvisibleValues: "Xóa giá trị câu hỏi ẩn",
    cookieName: "Giới hạn một phản hồi",
    partialSendEnabled: "Tự động lưu tiến trình khảo sát khi thay đổi trang",
    storeOthersAsComment:
      'Lưu giá trị tùy chọn "Khác" dưới dạng thuộc tính riêng',
    showPageTitles: "Hiển thị tiêu đề trang",
    showPageNumbers: "Hiển thị số trang",
    pagePrevText: 'Văn bản nút "Trang trước"',
    pageNextText: 'Văn bản nút "Trang tiếp theo"',
    completeText: 'Văn bản nút "Hoàn thành khảo sát"',
    previewText: 'Văn bản nút "Xem lại câu trả lời"',
    editText: 'Văn bản nút "Chỉnh sửa câu trả lời"',
    startSurveyText: 'Văn bản nút "Bắt đầu khảo sát"',
    showNavigationButtons: "Hiển thị nút điều hướng",
    navigationButtonsLocation: "Căn chỉnh nút điều hướng",
    showPrevButton: 'Hiển thị nút "Trang trước"',
    firstPageIsStartPage: "Trang đầu tiên là trang bắt đầu",
    showCompletePage: 'Hiển thị trang "Cảm ơn"',
    autoAdvanceEnabled: "Tự động chuyển sang trang tiếp theo",
    autoAdvanceAllowComplete: "Tự động hoàn thành khảo sát",
    showProgressBar: "Hiển thị thanh tiến trình",
    progressBarLocation: "Căn chỉnh thanh tiến trình",
    questionTitleLocation: "Căn chỉnh tiêu đề câu hỏi",
    questionTitleWidth: "Chiều rộng tiêu đề câu hỏi",
    requiredMark: "Biểu tượng bắt buộc",
    questionTitleTemplate:
      "Mẫu tiêu đề câu hỏi, mặc định là: '{no}. {require} {title}'",
    questionErrorLocation: "Căn chỉnh thông báo lỗi",
    autoFocusFirstQuestion: "Tập trung vào câu hỏi đầu tiên trên trang mới",
    questionOrder: "Thứ tự câu hỏi",
    timeLimit: "Giới hạn thời gian để hoàn thành khảo sát",
    timeLimitPerPage: "Giới hạn thời gian để hoàn thành một trang",
    showTimer: "Sử dụng bộ đếm thời gian",
    timerLocation: "Căn chỉnh bộ đếm thời gian",
    timerInfoMode: "Chế độ bộ đếm thời gian",
    renderMode: "Chế độ hiển thị bảng",
    allowAddPanel: "Cho phép thêm bảng",
    allowRemovePanel: "Cho phép xóa bảng",
    addPanelText: 'Văn bản nút "Thêm bảng"',
    removePanelText: 'Văn bản nút "Xóa bảng"',
    isSinglePage: "Hiển thị tất cả phần tử trên một trang",
    html: "Đánh dấu HTML",
    setValue: "Câu trả lời",
    dataFormat: "Định dạng lưu trữ",
    allowAddRows: "Cho phép thêm dòng",
    allowRemoveRows: "Cho phép xóa dòng",
    allowRowReorder: "Cho phép sắp xếp lại dòng",
    responsiveImageSizeHelp:
      "Không áp dụng nếu bạn chỉ định chiều rộng hoặc chiều cao khu vực hiển thị chính xác.",
    minImageWidth: "Chiều rộng khu vực hiển thị tối thiểu",
    maxImageWidth: "Chiều rộng khu vực hiển thị tối đa",
    minImageHeight: "Chiều cao khu vực hiển thị tối thiểu",
    maxImageHeight: "Chiều cao khu vực hiển thị tối đa",
    minValue: "Giá trị tối thiểu",
    maxValue: "Giá trị tối đa",
    caseInsensitive: "Không phân biệt chữ hoa chữ thường",
    minLength: "Độ dài tối thiểu (theo ký tự)",
    allowDigits: "Cho phép số",
    minCount: "Số lượng tối thiểu",
    maxCount: "Số lượng tối đa",
    regex: "Biểu thức chính quy",
    surveyvalidator: {
      text: "Thông báo lỗi",
      expression: "Biểu thức xác thực",
    },
    totalText: "Tiêu đề dòng tổng",
    totalType: "Phương pháp tổng hợp",
    totalExpression: "Biểu thức giá trị tổng",
    totalDisplayStyle: "Định dạng hiển thị giá trị tổng",
    totalCurrency: "Tiền tệ",
    totalFormat: "Chuỗi định dạng",
    logo: "Logo khảo sát",
    questionsOnPageMode: "Bố cục khảo sát",
    maxTextLength: "Giới hạn độ dài câu trả lời",
    maxCommentLength: "Giới hạn độ dài bình luận",
    commentAreaRows: "Chiều cao khu vực bình luận (theo dòng)",
    autoGrowComment: "Tự động mở rộng khu vực văn bản",
    allowResizeComment:
      "Cho phép người dùng thay đổi kích thước khu vực văn bản",
    textUpdateMode: "Cập nhật giá trị trường nhập",
    maskType: "Loại mặt nạ nhập",
    autoFocusFirstError: "Đặt tiêu điểm vào câu trả lời không hợp lệ đầu tiên",
    checkErrorsMode: "Chạy xác thực",
    validateVisitedEmptyFields: "Xác thực các trường trống khi mất tiêu điểm",
    navigateToUrl: "Chuyển hướng đến liên kết bên ngoài sau khi gửi",
    navigateToUrlOnCondition: "Liên kết bên ngoài động",
    completedBeforeHtml:
      "Đánh dấu hiển thị nếu người dùng đã điền khảo sát này",
    completedHtml: 'Đánh dấu trang "Cảm ơn"',
    completedHtmlOnCondition: 'Đánh dấu trang "Cảm ơn" động',
    loadingHtml: "Đánh dấu hiển thị trong khi mô hình khảo sát đang tải",
    commentText: "Văn bản khu vực bình luận",
    autocomplete: "Loại tự động hoàn thành",
    labelTrue: 'Nhãn cho "Đúng"',
    labelFalse: 'Nhãn cho "Sai"',
    allowClear: "Hiển thị nút Xóa",
    searchMode: "Chế độ tìm kiếm",
    displayStyle: "Định dạng hiển thị",
    format: "Chuỗi định dạng",
    maximumFractionDigits: "Số chữ số thập phân tối đa",
    minimumFractionDigits: "Số chữ số thập phân tối thiểu",
    useGrouping: "Hiển thị dấu phân cách nhóm",
    allowMultiple: "Cho phép tải lên nhiều tệp",
    allowImagesPreview: "Xem trước hình ảnh đã tải lên",
    acceptedTypes: "Loại tệp được chấp nhận",
    waitForUpload: "Đợi tải lên hoàn tất",
    needConfirmRemoveFile: "Xác nhận xóa tệp",
    detailPanelMode: "Căn chỉnh mở rộng dòng",
    minRowCount: "Số dòng tối thiểu",
    maxRowCount: "Số dòng tối đa",
    confirmDelete: "Xác nhận xóa dòng",
    confirmDeleteText: "Thông báo xác nhận",
    panelCount: "Số bảng ban đầu",
    minPanelCount: "Số bảng tối thiểu",
    maxPanelCount: "Số bảng tối đa",
    panelsState: "Trạng thái thu gọn bảng bên trong",
    prevPanelText: 'Văn bản nút "Bảng trước"',
    nextPanelText: 'Văn bản nút "Bảng tiếp theo"',
    removePanelButtonLocation: 'Căn chỉnh nút "Xóa bảng"',
    hideIfRowsEmpty: "Ẩn câu hỏi nếu không có dòng",
    hideColumnsIfEmpty: "Ẩn cột nếu không có dòng",
    rateValues: "Giá trị đánh giá tùy chỉnh",
    rateCount: "Số lượng đánh giá",
    autoGenerate: "Cấu hình đánh giá",
    hideIfChoicesEmpty: "Ẩn câu hỏi nếu không có lựa chọn",
    minWidth: "Chiều rộng tối thiểu",
    maxWidth: "Chiều rộng tối đa",
    width: "Chiều rộng",
    showHeader: "Hiển thị tiêu đề cột",
    horizontalScroll: "Hiển thị thanh cuộn ngang",
    columnMinWidth: "Chiều rộng cột tối thiểu",
    rowTitleWidth: "Chiều rộng tiêu đề dòng",
    valueTrue: 'Giá trị lưu khi chọn "Đúng"',
    valueFalse: 'Giá trị lưu khi chọn "Sai"',
    minErrorText: 'Thông báo lỗi "Giá trị dưới mức tối thiểu"',
    maxErrorText: 'Thông báo lỗi "Giá trị vượt quá tối đa"',
    otherErrorText: 'Thông báo lỗi "Bình luận trống"',
    keyDuplicationError: "Thông báo lỗi cho câu trả lời trùng lặp",
    minSelectedChoices: "Số lựa chọn tối thiểu để chọn",
    maxSelectedChoices: "Số lựa chọn tối đa để chọn",
    logoWidth: "Chiều rộng logo",
    logoHeight: "Chiều cao logo",
    readOnly: "Chỉ đọc",
    enableIf: "Tắt chế độ chỉ đọc nếu",
    noRowsText: 'Thông báo "Không có dòng"',
    separateSpecialChoices: "Tách các lựa chọn đặc biệt",
    choicesFromQuestion: "Sao chép lựa chọn từ câu hỏi sau",
    choicesFromQuestionMode: "Lựa chọn nào để sao chép",
    choiceValuesFromQuestion:
      "Sử dụng giá trị từ cột ma trận hoặc câu hỏi bảng sau làm ID lựa chọn",
    choiceTextsFromQuestion:
      "Sử dụng giá trị từ cột ma trận hoặc câu hỏi bảng sau làm văn bản lựa chọn",
    progressBarShowPageTitles: "Hiển thị tiêu đề trang trong thanh tiến trình",
    progressBarShowPageNumbers: "Hiển thị số trang trong thanh tiến trình",
    showCommentArea: "Thêm hộp bình luận",
    commentPlaceholder: "Văn bản trình giữ chỗ cho hộp bình luận",
    displayRateDescriptionsAsExtremeItems:
      "Hiển thị nhãn dưới dạng giá trị cực đại",
    rowOrder: "Thứ tự dòng",
    columnsLayout: "Bố cục cột",
    columnColCount: "Số cột lồng nhau",
    correctAnswer: "Câu trả lời đúng",
    defaultPanelValue: "Giá trị mặc định",
    cells: "Văn bản ô",
    fileInputPlaceholder: "Chọn tệp hoặc dán liên kết tệp...",
    keyName: "Ngăn chặn câu trả lời trùng lặp trong cột sau",
    itemvalue: {
      visibleIf: "Hiển thị tùy chọn nếu",
      enableIf: "Cho phép chọn tùy chọn nếu",
    },
    "itemvalue@rows": {
      visibleIf: "Hiển thị dòng nếu",
      enableIf: "Cho phép chỉnh sửa dòng nếu",
    },
    imageitemvalue: {
      text: "Văn bản thay thế",
    },
    logoPosition: "Căn chỉnh logo",
    addLogo: "Thêm logo...",
    changeLogo: "Thay đổi logo...",
    logoPositions: {
      none: "Xóa logo",
      left: "Trái",
      right: "Phải",
      top: "Trên cùng",
      bottom: "Dưới cùng",
    },
    previewMode: "Chế độ xem trước",
    gridLayoutEnabled: "Bật bố cục lưới",
    gridLayoutColumns: "Cột lưới",
    maskSettings: "Cài đặt mặt nạ",
    detailErrorLocation: "Căn chỉnh thông báo lỗi mở rộng dòng",
    // Creator tabs
    tabs: {
      panel: {
        layout: "Bố cục bảng",
      },
      general: "Tổng quan",
      fileOptions: "Tùy chọn",
      html: "Trình chỉnh sửa HTML",
      columns: "Cột",
      rows: "Dòng",
      choices: "Tùy chọn lựa chọn",
      items: "Mục",
      visibleIf: "Hiển thị nếu",
      enableIf: "Có thể chỉnhParty nếu",
      requiredIf: "Bắt buộc nếu",
      rateValues: "Giá trị đánh giá",
      choicesByUrl: "Lựa chọn từ dịch vụ web",
      matrixChoices: "Lựa chọn mặc định",
      multipleTextItems: "Trường nhập văn bản",
      numbering: "Đánh số",
      validators: "Trình xác thực",
      navigation: "Điều hướng",
      question: "Cài đặt câu hỏi",
      pages: "Trang",
      timer: "Chế độ thi",
      calculatedValues: "Giá trị tính toán",
      triggers: "Trình kích hoạt",
      templateTitle: "Mẫu tiêu đề",
      totals: "Tổng",
      logic: "Điều kiện",
      mask: "Cài đặt mặt nạ nhập",
      layout: {
        panel: "Bố cục bảng",
        question: "Bố cục",
        base: "Bố cục",
      },
      data: "Dữ liệu",
      validation: "Xác thực",
      cells: "Văn bản ô riêng lẻ",
      showOnCompleted: 'Trang "Cảm ơn"',
      logo: "Logo trong tiêu đề khảo sát",
      slider: "Thanh trượt",
      expression: "Biểu thức",
      questionSettings: "Cài đặt câu hỏi",
      header: "Tiêu đề",
      background: "Nền",
      appearance: "Giao diện",
      accentColors: "Màu nhấn",
      surfaceBackground: "Nền bề mặt",
      scaling: "Tỷ lệ",
      others: "Khác",
    },
    editProperty: "Chỉnh sửa thuộc tính '{0}'",
    items: "Mục",
    choicesVisibleIf: "Hiển thị lựa chọn nếu",
    choicesEnableIf: "Cho phép chọn lựa chọn nếu",
    columnsEnableIf: "Hiển thị cột nếu",
    rowsEnableIf: "Hiển thị dòng nếu",
    innerIndent: "Tăng khoảng cách thụt lề bên trong",
    copyDefaultValueFromLastEntry:
      "Sử dụng câu trả lời từ mục nhập cuối cùng làm mặc định",
    enterNewValue: "Vui lòng nhập giá trị.",
    noquestions: "Không có câu hỏi nào trong khảo sát.",
    createtrigger: "Vui lòng tạo trình kích hoạt",
    titleKeyboardAdornerTip: "Nhấn nút enter để chỉnh sửa",
    keyboardAdornerTip:
      "Nhấn nút enter để chỉnh sửa mục, nhấn nút delete để xóa mục, nhấn alt cộng với mũi tên lên hoặc xuống để di chuyển mục",
    triggerOn: "Bật ",
    triggerMakePagesVisible: "Hiển thị trang",
    triggerMakeQuestionsVisible: "Hiển thị phần tử",
    triggerCompleteText: "Hoàn thành khảo sát nếu thành công.",
    triggerNotSet: "Trình kích hoạt chưa được đặt",
    triggerRunIf: "Chạy nếu",
    triggerSetToName: "Thay đổi giá trị của: ",
    triggerFromName: "Sao chép giá trị từ: ",
    triggerRunExpression: "Chạy biểu thức này",
    triggerSetValue: "đến: ",
    triggerGotoName: "Đi đến câu hỏi",
    triggerIsVariable: "Không đưa biến vào kết quả khảo sát.",
    triggerRunExpressionEmpty: "Vui lòng nhập biểu thức hợp lệ",
    emptyExpressionPlaceHolder: "Nhập biểu thức tại đây...",
    noFile: "Không có tệp nào được chọn",
    clearIfInvisible: "Xóa giá trị câu hỏi ẩn",
    valuePropertyName: "Lưu giá trị trong thuộc tính sau",
    searchEnabled: "Bật tìm kiếm khi nhập",
    hideSelectedItems: "Ẩn các mục đã chọn",
    closeOnSelect: "Thu gọn danh sách thả xuống khi chọn",
    verticalAlign: "Căn chỉnh dọc trong các ô",
    alternateRows: "Màu dòng xen kẽ",
    columnsVisibleIf: "Hiển thị cột nếu",
    rowsVisibleIf: "Hiển thị dòng nếu",
    otherPlaceholder: "Văn bản trình giữ chỗ cho hộp bình luận",
    filePlaceholder: "Văn bản trình giữ chỗ cho tệp cục bộ",
    photoPlaceholder: "Văn bản trình giữ chỗ cho máy ảnh",
    fileOrPhotoPlaceholder: "Văn bản trình giữ chỗ cho tệp cục bộ hoặc máy ảnh",
    rateType: "Biểu tượng đánh giá",
    url_placeholder: "Ví dụ: https://api.example.com/books",
    path_placeholder: "Ví dụ: categories.fiction",
    questionStartIndex_placeholder: "Ví dụ: a)",
    width_placeholder: "Ví dụ: 6in",
    minWidth_placeholder: "Ví dụ: 600px",
    maxWidth_placeholder: "Ví dụ: 50%",
    imageHeight_placeholder: "tự động",
    imageWidth_placeholder: "tự động",
    itemTitleWidth_placeholder: "Ví dụ: 100px",
    theme: {
      themeName: "Chủ đề",
      isPanelless: "Giao diện câu hỏi",
      editorPanel: "Nền và bán kính góc",
      questionPanel: "Nền và bán kính góc",
      primaryColor: "Màu nhấn",
      panelBackgroundTransparency: "Độ trong suốt của bảng và hộp câu hỏi",
      questionBackgroundTransparency: "Độ trong suốt của phần tử nhập",
      fontSize: "Kích thước phông chữ khảo sát",
      scale: "Hệ số tỷ lệ khảo sát",
      cornerRadius: "Bán kính góc",
      advancedMode: "Chế độ nâng cao",
      pageTitle: "Phông chữ tiêu đề",
      pageDescription: "Phông chữ mô tả",
      questionTitle: "Phông chữ tiêu đề",
      questionDescription: "Phông chữ mô tả",
      editorFont: "Phông chữ",
      backgroundOpacity: "Độ trong suốt",
      "--sjs-font-family": "Gia đình phông chữ khảo sát",
      "--sjs-general-backcolor-dim": "Màu nền",
      "--sjs-primary-backcolor": "Màu nền nhấn",
      "--sjs-primary-forecolor": "Màu chữ nhấn",
      "--sjs-special-red": "Màu thông báo lỗi",
      "--sjs-shadow-small": "Hiệu ứng bóng",
      "--sjs-shadow-inner": "Hiệu ứng bóng",
      "--sjs-border-default": "Màu sắc",
    },
    "header@header": {
      headerView: "Chế độ xem",
      logoPosition: "Căn chỉnh logo",
      surveyTitle: "Phông chữ tiêu đề khảo sát",
      surveyDescription: "Phông chữ mô tả khảo sát",
      headerTitle: "Phông chữ tiêu đề khảo sát",
      headerDescription: "Phông chữ mô tả khảo sát",
      inheritWidthFrom: "Chiều rộng khu vực nội dung",
      textAreaWidth: "Chiều rộng văn bản",
      backgroundColorSwitch: "Màu nền",
      backgroundImage: "Hình nền",
      backgroundImageOpacity: "Độ trong suốt",
      overlapEnabled: "Chồng lấn",
      logoPositionX: "Căn chỉnh logo",
      titlePositionX: "Căn chỉnh tiêu đề khảo sát",
      descriptionPositionX: "Căn chỉnh mô tả khảo sát",
    },
  },
  // Property values
  pv: {
    true: "đúng",
    false: "sai",
    file: "Tệp cục bộ",
    camera: "Máy ảnh",
    "file-camera": "Tệp cục bộ hoặc máy ảnh",
    inherit: "Kế thừa",
    show: "Hiển thị",
    hide: "Ẩn",
    default: "Kế thừa",
    initial: "Ban đầu",
    random: "Ngẫu nhiên",
    collapsed: "Thu gọn",
    expanded: "Mở rộng",
    none: "Không có",
    asc: "Tăng dần",
    desc: "Giảm dần",
    indeterminate: "Không xác định",
    selected: "Đã chọn",
    unselected: "Chưa chọn",
    decimal: "thập phân",
    currency: "tiền tệ",
    percent: "phần trăm",
    firstExpanded: "Bảng đầu tiên được mở rộng",
    off: "Ẩn số câu hỏi",
    list: "Danh sách",
    carousel: "Băng chuyền",
    tab: "Tab",
    progressTop: "Điều hướng bảng + Thanh tiến trình ở trên",
    progressBottom: "Điều hướng bảng + Thanh tiến trình ở dưới",
    progressTopBottom: "Điều hướng bảng + Thanh tiến trình ở trên và dưới",
    horizontal: "Ngang",
    vertical: "Dọc",
    top: "Trên",
    bottom: "Dưới",
    topBottom: "Trên và dưới",
    both: "Cả hai",
    left: "Trái",
    right: "Phải",
    center: "Giữa",
    leftRight: "Trái và phải",
    middle: "Giữa",
    color: "màu",
    date: "ngày",
    datetime: "ngày giờ",
    "datetime-local": "ngày giờ cục bộ",
    email: "email",
    month: "tháng",
    number: "số",
    password: "mật khẩu",
    range: "phạm vi",
    tel: "điện thoại",
    text: "văn bản",
    time: "thời gian",
    url: "url",
    week: "tuần",
    hidden: "Ẩn",
    edit: "Có thể chỉnh sửa",
    display: "Chỉ đọc",
    contain: "Chứa",
    cover: "Bao phủ",
    fill: "Điền",
    next: "Tiếp theo",
    last: "Cuối cùng",
    onComplete: "Khi hoàn thành khảo sát",
    onHidden: "Khi câu hỏi bị ẩn",
    onHiddenContainer: "Khi câu hỏi hoặc bảng/trang của nó bị ẩn",
    clearInvisibleValues: {
      none: "Không bao giờ",
    },
    clearIfInvisible: {
      none: "Không bao giờ",
    },
    inputType: {
      color: "Màu",
      date: "Ngày",
      "datetime-local": "Ngày và Giờ",
      email: "Email",
      month: "Tháng",
      number: "Số",
      password: "Mật khẩu",
      range: "Phạm vi",
      tel: "Số điện thoại",
      text: "Văn bản",
      time: "Thời gian",
      url: "URL",
      week: "Tuần",
    },
    autocomplete: {
      name: "Họ tên đầy đủ",
      "honorific-prefix": "Tiền tố",
      "given-name": "Tên",
      "additional-name": "Tên đệm",
      "family-name": "Họ",
      "honorific-suffix": "Hậu tố",
      nickname: "Biệt danh",
      "organization-title": "Chức danh công việc",
      username: "Tên người dùng",
      "new-password": "Mật khẩu mới",
      "current-password": "Mật khẩu hiện tại",
      organization: "Tên tổ chức",
      "street-address": "Địa chỉ đường phố đầy đủ",
      "address-line1": "Dòng địa chỉ 1",
      "address-line2": "Dòng địa chỉ 2",
      "address-line3": "Dòng địa chỉ 3",
      "address-level4": "Địa chỉ cấp 4",
      "address-level3": "Địa chỉ cấp 3",
      "address-level2": "Địa chỉ cấp 2",
      "address-level1": "Địa chỉ cấp 1",
      country: "Mã quốc gia",
      "country-name": "Tên quốc gia",
      "postal-code": "Mã bưu điện",
      "cc-name": "Tên chủ thẻ",
      "cc-given-name": "Tên chủ thẻ",
      "cc-additional-name": "Tên đệm chủ thẻ",
      "cc-family-name": "Họ chủ thẻ",
      "cc-number": "Số thẻ tín dụng",
      "cc-exp": "Ngày hết hạn",
      "cc-exp-month": "Tháng hết hạn",
      "cc-exp-year": "Năm hết hạn",
      "cc-csc": "Mã bảo mật thẻ",
      "cc-type": "Loại thẻ tín dụng",
      "transaction-currency": "Tiền tệ giao dịch",
      "transaction-amount": "Số tiền giao dịch",
      language: "Ngôn ngữ ưu tiên",
      bday: "Sinh nhật",
      "bday-day": "Ngày sinh",
      "bday-month": "Tháng sinh",
      "bday-year": "Năm sinh",
      sex: "Giới tính",
      url: "URL trang web",
      photo: "Ảnh hồ sơ",
      tel: "Số điện thoại",
      "tel-country-code": "Mã quốc gia cho điện thoại",
      "tel-national": "Số điện thoại quốc gia",
      "tel-area-code": "Mã vùng",
      "tel-local": "Số điện thoại địa phương",
      "tel-local-prefix": "Tiền tố điện thoại địa phương",
      "tel-local-suffix": "Hậu tố điện thoại địa phương",
      "tel-extension": "Phần mở rộng điện thoại",
      email: "Địa chỉ email",
      impp: "Giao thức nhắn tin tức thời",
    },
    maskType: {
      none: "Không có",
      pattern: "Mẫu",
      numeric: "Số",
      datetime: "Ngày và Giờ",
      currency: "Tiền tệ",
    },
    inputTextAlignment: {
      auto: "Tự động",
      left: "Trái",
      right: "Phải",
    },
    all: "Tất cả",
    page: "Trang",
    survey: "Khảo sát",
    onNextPage: "Khi chuyển sang trang tiếp theo",
    onValueChanged: "Sau khi câu trả lời thay đổi",
    onValueChanging: "Trước khi câu trả lời thay đổi",
    questionsOnPageMode: {
      standard: "Cấu trúc gốc",
      singlePage: "Hiển thị tất cả câu hỏi trên một trang",
      questionPerPage: "Hiển thị một câu hỏi trên mỗi trang",
      inputPerPage: "Hiển thị một trường nhập trên mỗi trang",
    },
    noPreview: "Không xem trước",
    showAllQuestions: "Hiển thị tất cả câu hỏi",
    showAnsweredQuestions: "Chỉ hiển thị câu hỏi đã trả lời",
    allQuestions: "Hiển thị tất cả câu hỏi",
    answeredQuestions: "Chỉ hiển thị câu hỏi đã trả lời",
    pages: "Trang hoàn thành",
    questions: "Câu hỏi đã trả lời",
    requiredQuestions: "Câu hỏi bắt buộc đã trả lời",
    correctQuestions: "Câu trả lời hợp lệ",
    buttons: "Trang hoàn thành (giao diện nút)",
    underInput: "Dưới trường nhập",
    underTitle: "Dưới tiêu đề câu hỏi",
    onBlur: "Khi mất tiêu điểm",
    onTyping: "Trong khi nhập",
    underRow: "Dưới dòng",
    underRowSingle: "Dưới dòng, chỉ hiển thị một mở rộng dòng",
    auto: "Tự động",
    showNavigationButtons: {
      none: "Ẩn",
    },
    timerInfoMode: {
      combined: "Cả hai",
    },
    addRowButtonLocation: {
      default: "Dựa trên bố cục ma trận",
    },
    panelsState: {
      default: "Khóa",
      collapsed: "Thu gọn tất cả",
      expanded: "Mở rộng tất cả",
      firstExpanded: "Mở rộng đầu tiên",
    },
    widthMode: {
      static: "Tĩnh",
      responsive: "Thích ứng",
    },
    contentMode: {
      image: "Hình ảnh",
      video: "Video",
      youtube: "YouTube",
    },
    displayMode: {
      buttons: "Nút",
      dropdown: "Danh sách thả xuống",
    },
    rateColorMode: {
      default: "Mặc định",
      scale: "Thang màu",
    },
    scaleColorMode: {
      monochrome: "Đơn sắc",
      colored: "Có màu",
    },
    autoGenerate: {
      true: "Tự động tạo",
      false: "Thủ công",
    },
    rateType: {
      labels: "Nhãn",
      stars: "Ngôi sao",
      smileys: "Mặt cười",
    },
    state: {
      default: "Khóa",
    },
    showQuestionNumbers: {
      default: "Đánh số tự động",
      on: "Đánh số tự động",
      onPage: "Đặt lại trên mỗi trang",
      onpanel: "Đặt lại trên mỗi bảng",
      onPanel: "Đặt lại trên mỗi bảng",
      recursive: "Đánh số đệ quy",
      onSurvey: "Tiếp tục trên toàn khảo sát",
      off: "Không đánh số",
    },
    descriptionLocation: {
      underTitle: "Dưới tiêu đề câu hỏi",
      underInput: "Dưới trường nhập",
    },
    selectToRankAreasLayout: {
      horizontal: "Bên cạnh các lựa chọn",
      vertical: "Phía trên các lựa chọn",
    },
    displayStyle: {
      decimal: "Thập phân",
      currency: "Tiền tệ",
      percent: "Phần trăm",
      date: "Ngày",
    },
    totalDisplayStyle: {
      decimal: "Thập phân",
      currency: "Tiền tệ",
      percent: "Phần trăm",
      date: "Ngày",
    },
    rowOrder: {
      initial: "Gốc",
    },
    questionOrder: {
      initial: "Gốc",
    },
    progressBarLocation: {
      top: "Trên",
      bottom: "Dưới",
      topbottom: "Trên và dưới",
      aboveheader: "Phía trên tiêu đề",
      belowheader: "Phía dưới tiêu đề",
      off: "Ẩn",
    },
    sum: "Tổng",
    count: "Đếm",
    min: "Tối thiểu",
    max: "Tối đa",
    avg: "Trung bình",
    searchMode: {
      contains: "Chứa",
      startsWith: "Bắt đầu bằng",
    },
    backgroundImageFit: {
      auto: "Tự động",
      cover: "Bao phủ",
      contain: "Chứa",
      fill: "Điền",
      tile: "Lát gạch",
    },
    backgroundImageAttachment: {
      fixed: "Cố định",
      scroll: "Cuộn",
    },
    headerView: {
      basic: "Cơ bản",
      advanced: "Nâng cao",
    },
    inheritWidthFrom: {
      survey: "Giống khảo sát",
      container: "Giống bộ chứa",
    },
    backgroundColorSwitch: {
      none: "Không có",
      accentColor: "Màu nhấn",
      custom: "Tùy chỉnh",
    },
    colorPalette: {
      light: "Sáng",
      dark: "Tối",
    },
    isPanelless: {
      false: "Mặc định",
      true: "Không có bảng",
    },
    progressBarInheritWidthFrom: {
      survey: "Giống khảo sát",
      container: "Giống bộ chứa",
    },
  },
  // Operators
  op: {
    empty: "Trống",
    notempty: "Không trống",
    equal: "Bằng",
    notequal: "Không bằng",
    contains: "Chứa",
    notcontains: "Không chứa",
    anyof: "Bất kỳ trong",
    allof: "Tất cả trong",
    greater: "Lớn hơn",
    less: "Nhỏ hơn",
    greaterorequal: "Lớn hơn hoặc bằng",
    lessorequal: "Nhỏ hơn hoặc bằng",
    and: "và",
    or: "hoặc",
  },
  // Embed window
  ew: {
    angular: "Sử dụng phiên bản Angular",
    jquery: "Sử dụng phiên bản jQuery",
    knockout: "Sử dụng phiên bản Knockout",
    react: "Sử dụng phiên bản React",
    vue: "Sử dụng phiên bản Vue",
    bootstrap: "Cho khung bootstrap",
    modern: "Chủ đề hiện đại",
    default: "Chủ đề mặc định",
    orange: "Chủ đề cam",
    darkblue: "Chủ đề xanh đậm",
    darkrose: "Chủ đề hồng đậm",
    stone: "Chủ đề đá",
    winter: "Chủ đề mùa đông",
    winterstone: "Chủ đề đá mùa đông",
    showOnPage: "Hiển thị khảo sát trên trang",
    showInWindow: "Hiển thị khảo sát trong cửa sổ",
    loadFromServer: "Tải JSON khảo sát từ máy chủ",
    titleScript: "Kịch bản và kiểu dáng",
    titleHtml: "HTML",
    titleJavaScript: "JavaScript",
  },
  // Preview (Survey)
  ts: {
    selectPage: "Chọn trang để kiểm tra",
    showInvisibleElements: "Hiển thị phần tử ẩn",
    hideInvisibleElements: "Ẩn phần tử ẩn",
    prevPage: "Trước",
    nextPage: "Tiếp theo",
  },
  validators: {
    answercountvalidator: "Số lượng câu trả lời",
    emailvalidator: "Email",
    expressionvalidator: "Biểu thức",
    numericvalidator: "Số",
    regexvalidator: "Biểu thức chính quy",
    textvalidator: "Văn bản",
  },
  triggers: {
    completetrigger: "Hoàn thành khảo sát",
    setvaluetrigger: "Đặt câu trả lời",
    copyvaluetrigger: "Sao chép câu trả lời",
    skiptrigger: "Bỏ qua đến câu hỏi",
    runexpressiontrigger: "Chạy biểu thức",
    visibletrigger: "thay đổi khả năng hiển thị (đã lỗi thời)",
  },
  peplaceholder: {
    patternmask: {
      pattern: "Ví dụ: +1(999)-999-99-99",
    },
    datetimemask: {
      pattern: "Ví dụ: mm/dd/yyyy HH:MM:ss",
    },
    currencymask: {
      prefix: "Ví dụ: $",
      suffix: "Ví dụ: USD",
    },
    panelbase: {
      questionTitleWidth: "Ví dụ: 200px",
    },
    panellayoutcolumn: {
      effectiveWidth: "Ví dụ: 30%",
      questionTitleWidth: "Ví dụ: 200px",
    },
  },
  pehelp: {
    panel: {
      name: "ID bảng không hiển thị với người trả lời.",
      description: "Nhập phụ đề bảng.",
      visibleIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện xác định khả năng hiển thị của bảng.",
      enableIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện tắt chế độ chỉ đọc cho bảng.",
      requiredIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện ngăn gửi khảo sát trừ khi ít nhất một câu hỏi lồng nhau có câu trả lời.",
      questionTitleLocation:
        'Áp dụng cho tất cả câu hỏi trong bảng này. Khi đặt thành "Ẩn", nó cũng ẩn mô tả câu hỏi. Nếu muốn ghi đè cài đặt này, hãy xác định quy tắc căn chỉnh tiêu đề cho các câu hỏi riêng lẻ. Tùy chọn "Kế thừa" áp dụng cài đặt cấp trang (nếu có) hoặc cấp khảo sát ("Trên cùng" theo mặc định).',
      questionTitleWidth:
        "Đặt chiều rộng nhất quán cho tiêu đề câu hỏi khi chúng được căn chỉnh sang trái của hộp câu hỏi. Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
      questionErrorLocation:
        'Đặt vị trí của thông báo lỗi liên quan đến tất cả câu hỏi trong bảng. Tùy chọn "Kế thừa" áp dụng cài đặt cấp trang (nếu có) hoặc cấp khảo sát.',
      questionOrder:
        'Giữ thứ tự gốc của các câu hỏi hoặc ngẫu nhiên hóa chúng. Tùy chọn "Kế thừa" áp dụng cài đặt cấp trang (nếu có) hoặc cấp khảo sát.',
      page: "Đặt lại vị trí bảng đến cuối trang đã chọn.",
      innerIndent:
        "Thêm khoảng cách hoặc lề giữa nội dung bảng và viền trái của hộp bảng.",
      startWithNewLine:
        "Bỏ chọn để hiển thị bảng trên cùng một dòng với câu hỏi hoặc bảng trước đó. Cài đặt này không áp dụng nếu bảng là phần tử đầu tiên trong biểu mẫu của bạn.",
      state:
        'Chọn từ: "Mở rộng" - bảng được hiển thị đầy đủ và có thể thu gọn; "Thu gọn" - bảng chỉ hiển thị tiêu đề và mô tả và có thể mở rộng; "Khóa" - bảng được hiển thị đầy đủ và không thể thu gọn.',
      width:
        "Đặt chiều rộng của bảng tỷ lệ với các phần tử khảo sát khác trên cùng một dòng. Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
      showQuestionNumbers: "Gán số cho các câu hỏi lồng trong bảng này.",
      effectiveColSpan:
        "Chỉ định bảng này trải dài bao nhiêu cột trong bố cục lưới.",
      gridLayoutColumns:
        "Bảng này cho phép bạn cấu hình mỗi cột lưới trong bảng. Nó tự động đặt phần trăm chiều rộng cho mỗi cột dựa trên số lượng phần tử tối đa trong một dòng. Để tùy chỉnh bố cục lưới, hãy điều chỉnh các giá trị này theo cách thủ công và xác định chiều rộng tiêu đề cho tất cả câu hỏi trong mỗi cột.",
    },
    paneldynamic: {
      name: "ID bảng không hiển thị với người trả lời.",
      description: "Nhập phụ đề bảng.",
      visibleIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện xác định khả năng hiển thị của bảng.",
      enableIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện tắt chế độ chỉ đọc cho bảng.",
      requiredIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện ngăn gửi khảo sát trừ khi ít nhất một câu hỏi lồng nhau có câu trả lời.",
      templateQuestionTitleLocation:
        "Áp dụng cho tất cả câu hỏi trong bảng này. Nếu muốn ghi đè cài đặt này, hãy xác định quy tắc căn chỉnh tiêu đề cho các câu hỏi riêng lẻ. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp trang (nếu có) hoặc cấp khảo sát ('Trên cùng' theo mặc định).",
      templateQuestionTitleWidth:
        "Đặt chiều rộng nhất quán cho tiêu đề câu hỏi khi chúng được căn chỉnh sang trái của hộp câu hỏi. Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
      templateErrorLocation:
        "Đặt vị trí của thông báo lỗi liên quan đến câu hỏi có đầu vào không hợp lệ. Chọn giữa: 'Trên cùng' - văn bản lỗi được đặt ở đầu hộp câu hỏi; 'Dưới cùng' - văn bản lỗi được đặt ở cuối hộp câu hỏi. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp trang (nếu có) hoặc cấp khảo sát ('Trên cùng' theo mặc định).",
      errorLocation:
        "Đặt vị trí của thông báo lỗi liên quan đến tất cả câu hỏi trong bảng. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp trang (nếu có) hoặc cấp khảo sát.",
      page: "Đặt lại vị trí bảng đến cuối trang đã chọn.",
      innerIndent:
        "Thêm khoảng cách hoặc lề giữa nội dung bảng và viền trái của hộp bảng.",
      startWithNewLine:
        "Bỏ chọn để hiển thị bảng trên cùng một dòng với câu hỏi hoặc bảng trước đó. Cài đặt này không áp dụng nếu bảng là phần tử đầu tiên trong biểu mẫu của bạn.",
      state:
        "Chọn từ: 'Mở rộng' - bảng được hiển thị đầy đủ và có thể thu gọn; 'Thu gọn' - bảng chỉ hiển thị tiêu đề và mô tả và có thể mở rộng; 'Khóa' - bảng được hiển thị đầy đủ và không thể thu gọn.",
      width:
        "Đặt chiều rộng của bảng tỷ lệ với các phần tử khảo sát khác trên cùng một dòng. Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
      templateTitle:
        "Nhập mẫu cho tiêu đề bảng động. Sử dụng {panelIndex} cho vị trí chung của bảng và {visiblePanelIndex} cho thứ tự của nó trong số các bảng hiển thị. Chèn các trình giữ chỗ này vào mẫu để thêm số tự động.",
      templateTabTitle:
        "Nhập mẫu cho tiêu đề tab. Sử dụng {panelIndex} cho vị trí chung của bảng và {visiblePanelIndex} cho thứ tự của nó trong số các bảng hiển thị. Chèn các trình giữ chỗ này vào mẫu để thêm số tự động.",
      tabTitlePlaceholder:
        "Văn bản dự phòng cho tiêu đề tab được áp dụng khi mẫu tiêu đề tab không tạo ra giá trị có ý nghĩa.",
      templateVisibleIf:
        "Cài đặt này cho phép bạn kiểm soát khả năng hiển thị của các bảng riêng lẻ trong bảng động. Sử dụng trình giữ chỗ `{panel}` để tham chiếu đến bảng hiện tại trong biểu thức của bạn.",
      titleLocation:
        "Cài đặt này được tự động kế thừa bởi tất cả câu hỏi trong bảng này. Nếu muốn ghi đè cài đặt này, hãy xác định quy tắc căn chỉnh tiêu đề cho các câu hỏi riêng lẻ. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp trang (nếu có) hoặc cấp khảo sát ('Trên cùng' theo mặc định).",
      descriptionLocation:
        "Tùy chọn 'Kế thừa' áp dụng cài đặt cấp trang (nếu có) hoặc cấp khảo sát ('Dưới tiêu đề bảng' theo mặc định).",
      newPanelPosition:
        "Xác định vị trí của bảng mới được thêm vào. Theo mặc định, các bảng mới được thêm vào cuối. Chọn 'Tiếp theo' để chèn bảng mới sau bảng hiện tại.",
      copyDefaultValueFromLastEntry:
        "Sao chép câu trả lời từ bảng cuối cùng và gán chúng cho bảng động tiếp theo được thêm vào.",
      keyName:
        "Tham chiếu tên câu hỏi để yêu cầu người dùng cung cấp câu trả lời duy nhất cho câu hỏi này trong mỗi bảng.",
    },
    copyDefaultValueFromLastEntry:
      "Sao chép câu trả lời từ dòng cuối cùng và gán chúng cho dòng động tiếp theo được thêm vào.",
    defaultValueExpression:
      "Cài đặt này cho phép bạn gán giá trị câu trả lời mặc định dựa trên một biểu thức. Biểu thức có thể bao gồm các phép tính cơ bản - `{q1_id} + {q2_id}`, biểu thức Boolean, như `{age} > 60`, và các hàm: `iif()`, `today()`, `age()`, `min()`, `max()`, `avg()`, v.v. Giá trị được xác định bởi biểu thức này đóng vai trò là giá trị mặc định ban đầu có thể bị ghi đè bởi đầu vào thủ công của người trả lời.",
    resetValueIf:
      "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện xác định khi nào đầu vào của người trả lời được đặt lại về giá trị dựa trên 'Biểu thức giá trị mặc định' hoặc 'Biểu thức đặt giá trị' hoặc về giá trị 'Câu trả lời mặc định' (nếu một trong hai được đặt).",
    setValueIf:
      "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện xác định khi nào chạy 'Biểu thức đặt giá trị' và gán giá trị kết quả làm câu trả lời một cách động.",
    setValueExpression:
      "Xác định biểu thức xác định giá trị cần đặt khi các điều kiện trong quy tắc 'Đặt giá trị nếu' được đáp ứng. Biểu thức có thể bao gồm các phép tính cơ bản - `{q1_id} + {q2_id}`, biểu thức Boolean, như `{age} > 60`, và các hàm: `iif()`, `today()`, `age()`, `min()`, `max()`, `avg()`, v.v. Giá trị được xác định bởi biểu thức này có thể bị ghi đè bởi đầu vào thủ công của người trả lời.",
    gridLayoutEnabled:
      "Survey Creator cho phép bạn điều chỉnh thủ công chiều rộng nội tuyến của các phần tử biểu mẫu để kiểm soát bố cục. Nếu điều này không mang lại kết quả mong muốn, bạn có thể bật bố cục lưới, bố trí các phần tử biểu mẫu bằng hệ thống dựa trên cột. Để cấu hình các cột bố cục, chọn một trang hoặc bảng và sử dụng bảng 'Cài đặt câu hỏi' → 'Cột lưới'. Để điều chỉnh số lượng cột mà một câu hỏi trải dài, chọn câu hỏi đó và đặt giá trị mong muốn trong trường 'Bố cục' → 'Khoảng cột'.",
    question: {
      name: "ID câu hỏi không hiển thị với người trả lời.",
      description: "Nhập phụ đề câu hỏi.",
      visibleIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện xác định khả năng hiển thị của câu hỏi.",
      enableIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện tắt chế độ chỉ đọc cho câu hỏi.",
      requiredIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện ngăn khảo sát tiến hoặc gửi trừ khi câu hỏi nhận được câu trả lời.",
      startWithNewLine:
        "Bỏ chọn để hiển thị câu hỏi trên cùng một dòng với câu hỏi hoặc bảng trước đó. Cài đặt này không áp dụng nếu câu hỏi là phần tử đầu tiên trong biểu mẫu của bạn.",
      page: "Đặt lại vị trí câu hỏi đến cuối trang đã chọn.",
      state:
        "Chọn từ: 'Mở rộng' - hộp câu hỏi được hiển thị đầy đủ và có thể thu gọn; 'Thu gọn' - hộp câu hỏi chỉ hiển thị tiêu đề và mô tả và có thể mở rộng; 'Khóa' - hộp câu hỏi được hiển thị đầy đủ và không thể thu gọn.",
      titleLocation:
        "Ghi đè các quy tắc căn chỉnh tiêu đề được xác định ở cấp bảng, trang hoặc khảo sát. Khi đặt thành 'Ẩn', nó cũng ẩn mô tả câu hỏi. Tùy chọn 'Kế thừa' áp dụng các cài đặt cấp cao hơn (nếu có) hoặc cài đặt cấp khảo sát ('Trên cùng' theo mặc định).",
      descriptionLocation:
        "Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát ('Dưới tiêu đề câu hỏi' theo mặc định).",
      errorLocation:
        "Đặt vị trí của thông báo lỗi liên quan đến câu hỏi có đầu vào không hợp lệ. Chọn giữa: 'Trên cùng' - văn bản lỗi được đặt ở đầu hộp câu hỏi; 'Dưới cùng' - văn bản lỗi được đặt ở cuối hộp câu hỏi. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát ('Trên cùng' theo mặc định).",
      indent:
        "Thêm khoảng cách hoặc lề giữa nội dung câu hỏi và viền trái của hộp câu hỏi.",
      width:
        "Đặt chiều rộng của câu hỏi tỷ lệ với các phần tử khảo sát khác trên cùng một dòng. Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
      surveyvalidator: {
        expression:
          "Sử dụng biểu tượng đũa phép để đặt quy tắc xác thực cho câu hỏi.",
      },
      textUpdateMode:
        "Chọn từ: 'Khi mất tiêu điểm' - giá trị được cập nhật khi trường nhập mất tiêu điểm; 'Trong khi nhập' - giá trị được cập nhật trong thời gian thực, khi người dùng đang nhập. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát ('Khi mất tiêu điểm' theo mặc định).",
      url: "Bạn có thể sử dụng bất kỳ dịch vụ web nào làm nguồn dữ liệu cho các câu hỏi nhiều lựa chọn. Để điền giá trị lựa chọn, nhập URL của dịch vụ cung cấp dữ liệu.",
      searchMode: "Thao tác so sánh được sử dụng để lọc danh sách thả xuống.",
      textWrapEnabled:
        "Văn bản dài trong các tùy chọn lựa chọn sẽ tự động tạo ngắt dòng để vừa với menu thả xuống. Bỏ chọn nếu bạn muốn văn bản bị cắt.",
      effectiveColSpan:
        "Xác định câu hỏi này trải dài bao nhiêu cột trong bố cục lưới.",
    },
    signaturepad: {
      signatureWidth:
        "Đặt chiều rộng của khu vực chữ ký được hiển thị và hình ảnh kết quả.",
      signatureHeight:
        "Đặt chiều cao của khu vực chữ ký được hiển thị và hình ảnh kết quả.",
      signatureAutoScaleEnabled:
        "Chọn nếu bạn muốn khu vực chữ ký lấp đầy toàn bộ không gian có sẵn trong hộp câu hỏi trong khi duy trì tỷ lệ khung hình mặc định 3:2. Khi các giá trị chiều rộng và chiều cao tùy chỉnh được đặt, cài đặt này sẽ giữ tỷ lệ khung hình của các kích thước đó.",
    },
    file: {
      imageHeight: "Điều chỉnh chiều cao của hình ảnh trong kết quả khảo sát.",
      imageWidth: "Điều chỉnh chiều rộng của hình ảnh trong kết quả khảo sát.",
      allowImagesPreview:
        "Hiển thị bản xem trước hình thu nhỏ cho các tệp đã tải lên khi có thể. Bỏ chọn nếu bạn muốn hiển thị biểu tượng tệp thay thế.",
    },
    image: {
      contentMode:
        "Tùy chọn 'Tự động' tự động xác định chế độ hiển thị phù hợp - Hình ảnh, Video hoặc YouTube - dựa trên URL nguồn được cung cấp.",
    },
    imagepicker: {
      imageHeight: "Ghi đè các giá trị chiều cao tối thiểu và tối đa.",
      imageWidth: "Ghi đè các giá trị chiều rộng tối thiểu và tối đa.",
      choices:
        "'Giá trị' đóng vai trò là ID mục được sử dụng trong các quy tắc điều kiện; 'Văn bản' được hiển thị cho người trả lời.",
      contentMode:
        "Chọn giữa 'Hình ảnh' và 'Video' để đặt chế độ nội dung của bộ chọn phương tiện. Nếu chọn 'Hình ảnh', hãy đảm bảo rằng tất cả các tùy chọn được cung cấp là tệp hình ảnh ở các định dạng sau: JPEG, GIF, PNG, APNG, SVG, BMP, ICO. Tương tự, nếu chọn 'Video', hãy đảm bảo rằng tất cả các tùy chọn là liên kết trực tiếp đến tệp video ở các định dạng sau: MP4, MOV, WMV, FLV, AVI, MKV. Vui lòng lưu ý rằng các liên kết YouTube không được hỗ trợ cho tùy chọn video.",
    },
    text: {
      size: "Cài đặt này chỉ thay đổi kích thước trường nhập và không ảnh hưởng đến chiều rộng của hộp câu hỏi. Để giới hạn độ dài đầu vào được chấp nhận, hãy vào 'Xác thực' → 'Giới hạn ký tự tối đa'.",
    },
    comment: {
      rows: "Đặt số dòng hiển thị trong trường nhập. Nếu đầu vào chiếm nhiều dòng hơn, thanh cuộn sẽ xuất hiện.",
    },
    survey: {
      readOnly:
        "Chọn nếu bạn muốn ngăn người trả lời điền vào khảo sát của bạn.",
      progressBarLocation:
        "Đặt vị trí của thanh tiến trình. Giá trị 'Tự động' hiển thị thanh tiến trình phía trên hoặc dưới tiêu đề khảo sát.",
    },
    matrixdropdowncolumn: {
      name: "ID cột không hiển thị với người trả lời.",
      isUnique:
        "Khi được bật cho một cột, người trả lời phải cung cấp câu trả lời duy nhất cho mỗi câu hỏi trong cột này.",
      rows: "Đặt số dòng hiển thị trong trường nhập. Nếu đầu vào chiếm nhiều dòng hơn, thanh cuộn sẽ xuất hiện.",
      visibleIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện xác định khả năng hiển thị của cột.",
      enableIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện tắt chế độ chỉ đọc cho cột.",
      requiredIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện ngăn gửi khảo sát trừ khi ít nhất một câu hỏi lồng nhau có câu trả lời.",
      showInMultipleColumns:
        "Khi được chọn, tạo một cột riêng cho mỗi tùy chọn lựa chọn.",
      colCount:
        "Sắp xếp các tùy chọn lựa chọn trong bố cục đa cột. Khi đặt thành 0, các tùy chọn được hiển thị trên một dòng. Khi đặt thành -1, giá trị thực tế được kế thừa từ thuộc tính 'Số cột lồng nhau' của ma trận cha.",
    },
    caseInsensitive:
      "Chọn nếu các chữ cái in hoa và thường trong biểu thức chính quy phải được coi là tương đương.",
    widthMode:
      "Chọn từ: 'Tĩnh' - đặt chiều rộng cố định; 'Thích ứng' - làm cho khảo sát chiếm toàn bộ chiều rộng của màn hình; 'Tự động' - áp dụng một trong hai tùy thuộc vào loại câu hỏi được sử dụng.",
    cookieName:
      "Gán giá trị cookie duy nhất cho khảo sát của bạn. Cookie sẽ được đặt trong trình duyệt của người trả lời khi hoàn thành khảo sát để ngăn gửi lại khảo sát.",
    logo: "Dán liên kết hình ảnh (không giới hạn kích thước) hoặc nhấp vào biểu tượng thư mục để duyệt tệp từ máy tính của bạn (tối đa 64KB).",
    logoWidth: "Đặt chiều rộng logo theo đơn vị CSS (px, %, in, pt, v.v.).",
    logoHeight: "Đặt chiều cao logo theo đơn vị CSS (px, %, in, pt, v.v.).",
    logoFit:
      "Chọn từ: 'Không' - hình ảnh giữ nguyên kích thước gốc; 'Chứa' - hình ảnh được điều chỉnh kích thước để vừa khít trong khi duy trì tỷ lệ khung hình; 'Bao phủ' - hình ảnh lấp đầy toàn bộ hộp trong khi duy trì tỷ lệ khung hình; 'Điền' - hình ảnh được kéo dài để lấp đầy hộp mà không duy trì tỷ lệ khung hình.",
    autoAdvanceEnabled:
      "Chọn nếu bạn muốn khảo sát tự động chuyển sang trang tiếp theo khi người trả lời đã trả lời tất cả các câu hỏi trên trang hiện tại. Tính năng này sẽ không áp dụng nếu câu hỏi cuối cùng trên trang là câu hỏi mở hoặc cho phép nhiều câu trả lời.",
    autoAdvanceAllowComplete:
      "Chọn nếu bạn muốn khảo sát hoàn thành tự động sau khi người trả lời trả lời tất cả các câu hỏi.",
    showNavigationButtons:
      "Đặt khả năng hiển thị của các nút điều hướng trên trang.",
    navigationButtonsLocation: "Đặt vị trí của các nút điều hướng trên trang.",
    showPreviewBeforeComplete:
      "Bật trang xem trước với tất cả hoặc chỉ các câu hỏi đã trả lời.",
    questionTitleLocation:
      "Áp dụng cho tất cả các câu hỏi trong khảo sát. Cài đặt này có thể bị ghi đè bởi các quy tắc căn chỉnh tiêu đề ở cấp thấp hơn: bảng, trang hoặc câu hỏi. Cài đặt cấp thấp hơn sẽ ghi đè những cài đặt ở cấp cao hơn.",
    requiredMark:
      "Biểu tượng hoặc chuỗi biểu tượng cho biết câu trả lời là bắt buộc.",
    questionStartIndex: "Nhập số hoặc chữ cái mà bạn muốn bắt đầu đánh số.",
    questionErrorLocation:
      "Đặt vị trí của thông báo lỗi liên quan đến câu hỏi có đầu vào không hợp lệ. Chọn giữa: 'Trên cùng' - văn bản lỗi được đặt ở đầu hộp câu hỏi; 'Dưới cùng' - văn bản lỗi được đặt ở cuối hộp câu hỏi.",
    autoFocusFirstQuestion:
      "Chọn nếu bạn muốn trường nhập đầu tiên trên mỗi trang sẵn sàng để nhập văn bản.",
    questionOrder:
      "Giữ nguyên thứ tự gốc của các câu hỏi hoặc ngẫu nhiên hóa chúng. Hiệu ứng của cài đặt này chỉ hiển thị trong tab Xem trước.",
    maxTextLength: "Chỉ dành cho câu hỏi nhập văn bản.",
    maxCommentLength: "Chỉ dành cho bình luận câu hỏi.",
    commentAreaRows:
      "Đặt số dòng hiển thị trong khu vực văn bản cho bình luận câu hỏi. Nếu đầu vào chiếm nhiều dòng hơn, thanh cuộn sẽ xuất hiện.",
    autoGrowComment:
      "Chọn nếu bạn muốn bình luận câu hỏi và câu hỏi Văn bản dài tự động tăng chiều cao dựa trên độ dài văn bản được nhập.",
    allowResizeComment:
      "Chỉ dành cho bình luận câu hỏi và câu hỏi Văn bản dài.",
    calculatedValues:
      "Các biến tùy chỉnh đóng vai trò là biến trung gian hoặc phụ trợ được sử dụng trong các phép tính biểu mẫu. Chúng lấy đầu vào của người trả lời làm giá trị nguồn. Mỗi biến tùy chỉnh có tên duy nhất và biểu thức mà nó dựa trên.",
    includeIntoResult:
      "Chọn nếu bạn muốn giá trị tính toán của biểu thức được lưu cùng với kết quả khảo sát.",
    triggers:
      "Trình kích hoạt là sự kiện hoặc điều kiện dựa trên một biểu thức. Khi biểu thức được đánh giá là 'đúng', một trình kích hoạt sẽ kích hoạt một hành động. Hành động này có thể tùy chọn có một câu hỏi mục tiêu mà nó ảnh hưởng.",
    clearInvisibleValues:
      "Chọn xem có nên xóa giá trị cho các câu hỏi bị ẩn bởi logic điều kiện hay không và khi nào thực hiện.",
    textUpdateMode:
      "Chọn từ: 'Khi mất tiêu điểm' - giá trị được cập nhật khi trường nhập mất tiêu điểm; 'Trong khi nhập' - giá trị được cập nhật trong thời gian thực, khi người dùng đang nhập.",
    columns:
      "Giá trị bên trái đóng vai trò là ID cột được sử dụng trong các quy tắc điều kiện, giá trị bên phải được hiển thị cho người trả lời.",
    rows: "Giá trị bên trái đóng vai trò là ID dòng được sử dụng trong các quy tắc điều kiện, giá trị bên phải được hiển thị cho người trả lời.",
    columnMinWidth: "Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
    rowTitleWidth: "Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
    totalText:
      "Chỉ hiển thị nếu ít nhất một cột hiển thị giá trị tổng được đặt với 'Phương pháp tổng hợp' hoặc 'Biểu thức giá trị tổng'.",
    cellErrorLocation:
      "Đặt vị trí của thông báo lỗi liên quan đến ô có đầu vào không hợp lệ. Tùy chọn 'Kế thừa' áp dụng cài đặt từ thuộc tính 'Căn chỉnh thông báo lỗi'.",
    detailErrorLocation:
      "Đặt vị trí của thông báo lỗi cho các câu hỏi lồng trong các phần chi tiết. Tùy chọn 'Kế thừa' áp dụng cài đặt từ thuộc tính 'Căn chỉnh thông báo lỗi'.",
    keyDuplicationError:
      "Khi thuộc tính 'Ngăn chặn câu trả lời trùng lặp' được bật, người trả lời cố gắng gửi một mục trùng lặp sẽ nhận được thông báo lỗi sau.",
    totalExpression:
      "Cho phép bạn tính toán giá trị tổng dựa trên một biểu thức. Biểu thức có thể bao gồm các phép tính cơ bản (`{q1_id} + {q2_id}`), biểu thức Boolean (`{age} > 60`) và các hàm ('iif()`, `today()`, `age()`, `min()`, `max()`, `avg()`, v.v.).",
    confirmDelete: "Kích hoạt lời nhắc yêu cầu xác nhận xóa dòng.",
    keyName:
      "Tham chiếu ID cột để yêu cầu người dùng cung cấp câu trả lời duy nhất cho mỗi câu hỏi trong cột được chỉ định.",
    description: "Nhập phụ đề.",
    locale:
      "Chọn ngôn ngữ để bắt đầu tạo khảo sát. Để thêm bản dịch, chuyển sang ngôn ngữ mới và dịch văn bản gốc tại đây hoặc trong tab Bản dịch.",
    detailPanelMode:
      "Đặt vị trí của phần chi tiết liên quan đến một dòng. Chọn từ: 'Không' - không thêm phần mở rộng; 'Dưới dòng' - phần mở rộng dòng được đặt dưới mỗi dòng của ma trận; 'Dưới dòng, chỉ hiển thị một phần mở rộng dòng' - phần mở rộng chỉ hiển thị dưới một dòng duy nhất, các phần mở rộng dòng còn lại được thu gọn.",
    imageFit:
      "Chọn từ: 'Không' - hình ảnh giữ nguyên kích thước gốc; 'Chứa' - hình ảnh được điều chỉnh kích thước để vừa khít trong khi duy trì tỷ lệ khung hình; 'Bao phủ' - hình ảnh lấp đầy toàn bộ hộp trong khi duy trì tỷ lệ khung hình; 'Điền' - hình ảnh được kéo dài để lấp đầy hộp mà không duy trì tỷ lệ khung hình.",
    autoGrow:
      "Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát ('Tắt' theo mặc định).",
    allowResize:
      "Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát ('Bật' theo mặc định).",
    timeLimit:
      "Khoảng thời gian tính bằng giây sau đó khảo sát tự động chuyển sang trang 'Cảm ơn'. Khi đặt thành 0, đếm thời gian đã dành cho khảo sát.",
    timeLimitPerPage:
      "Khoảng thời gian tính bằng giây sau đó khảo sát tự động chuyển sang trang tiếp theo. Ẩn nút điều hướng 'Trước đó'. Khi đặt thành 0, đếm thời gian đã dành trên trang hiện tại.",
    validateVisitedEmptyFields:
      "Bật tùy chọn này để kích hoạt xác thực khi người dùng tập trung vào trường nhập trống và sau đó rời khỏi nó mà không thực hiện bất kỳ thay đổi nào.",
    page: {
      name: "ID trang không hiển thị với người trả lời.",
      description: "Nhập phụ đề trang.",
      navigationTitle:
        "Chữ hiển thị trên nút điều hướng trong thanh tiến trình hoặc mục lục (TOC). Nếu để trống, nút điều hướng sẽ sử dụng tiêu đề trang hoặc tên trang. Để bật thanh tiến trình hoặc TOC, vào 'Khảo sát' → 'Điều hướng'.",
      timeLimit:
        "Khoảng thời gian tính bằng giây sau đó khảo sát tự động chuyển sang trang tiếp theo. Ẩn nút điều hướng 'Trước đó'. Khi đặt thành 0, đếm thời gian đã dành trên trang hiện tại.",
      visibleIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện xác định khả năng hiển thị của trang.",
      enableIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện tắt chế độ chỉ đọc cho trang.",
      requiredIf:
        "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện ngăn gửi khảo sát trừ khi ít nhất một câu hỏi lồng nhau có câu trả lời.",
      questionTitleLocation:
        "Áp dụng cho tất cả các câu hỏi trong trang này. Khi đặt thành 'Ẩn', nó cũng ẩn mô tả câu hỏi. Nếu muốn ghi đè cài đặt này, hãy xác định quy tắc căn chỉnh tiêu đề cho các câu hỏi hoặc bảng riêng lẻ. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát ('Trên cùng' theo mặc định).",
      questionTitleWidth:
        "Đặt chiều rộng nhất quán cho tiêu đề câu hỏi khi chúng được căn chỉnh sang trái của hộp câu hỏi. Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
      questionErrorLocation:
        "Đặt vị trí của thông báo lỗi liên quan đến câu hỏi có đầu vào không hợp lệ. Chọn giữa: 'Trên cùng' - văn bản lỗi được đặt ở đầu hộp câu hỏi; 'Dưới cùng' - văn bản lỗi được đặt ở cuối hộp câu hỏi. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát ('Trên cùng' theo mặc định).",
      questionOrder:
        "Giữ nguyên thứ tự gốc của các câu hỏi hoặc ngẫu nhiên hóa chúng. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát ('Gốc' theo mặc định). Hiệu ứng của cài đặt này chỉ hiển thị trong tab Xem trước.",
      showNavigationButtons:
        "Đặt khả năng hiển thị của các nút điều hướng trên trang. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát, mặc định là 'Hiển thị'.",
      gridLayoutColumns:
        "Bảng này cho phép bạn cấu hình mỗi cột lưới trên trang. Nó tự động đặt phần trăm chiều rộng cho mỗi cột dựa trên số lượng phần tử tối đa trong một dòng. Để tùy chỉnh bố cục lưới, hãy điều chỉnh các giá trị này theo cách thủ công và xác định chiều rộng tiêu đề cho tất cả câu hỏi trong mỗi cột.",
    },
    timerLocation: "Đặt vị trí của bộ đếm thời gian trên trang.",
    panelsState:
      "Chọn từ: 'Khóa' - người dùng không thể mở rộng hoặc thu gọn các bảng; 'Thu gọn tất cả' - tất cả các bảng bắt đầu ở trạng thái thu gọn; 'Mở rộng tất cả' - tất cả các bảng bắt đầu ở trạng thái mở rộng; 'Mở rộng đầu tiên' - chỉ bảng đầu tiên được mở rộng ban đầu. Áp dụng nếu 'Chế độ hiển thị bảng' được đặt thành 'Danh sách' và thuộc tính 'Mẫu tiêu đề bảng' được chỉ định.",
    imageLinkName:
      "Nhập tên thuộc tính chung trong mảng các đối tượng chứa các URL tệp hình ảnh hoặc video mà bạn muốn hiển thị trong danh sách lựa chọn.",
    choices:
      "Giá trị bên trái đóng vai trò là ID mục được sử dụng trong các quy tắc điều kiện, giá trị bên phải được hiển thị cho người trả lời.",
    title: "Nhập tiêu đề thân thiện với người dùng để hiển thị.",
    waitForUpload:
      "Đảm bảo rằng người dùng không hoàn thành khảo sát cho đến khi tệp được tải lên.",
    minWidth: "Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
    maxWidth: "Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
    width: "Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
    valueName:
      "Định danh kết nối là khóa tùy chỉnh mà bạn có thể gán cho nhiều câu hỏi để liên kết chúng và đồng bộ hóa giá trị của chúng. Các giá trị này sẽ được hợp nhất thành một mảng hoặc đối tượng duy nhất và lưu trữ trong kết quả khảo sát bằng cách sử dụng khóa làm tên thuộc tính.",
    defaultDisplayValue:
      "Giá trị hiển thị trong các câu hỏi HTML và trong tiêu đề và mô tả động của các phần tử khảo sát khi giá trị câu hỏi trống.",
    useDisplayValuesInDynamicTexts:
      "Trong các loại câu hỏi chọn một và chọn nhiều, mỗi tùy chọn lựa chọn có ID và giá trị hiển thị. Khi được chọn, cài đặt này hiển thị giá trị hiển thị thay vì giá trị ID trong các câu hỏi HTML và tiêu đề và mô tả động của các phần tử khảo sát.",
    clearIfInvisible:
      "Chọn xem có nên xóa giá trị câu hỏi bị ẩn bởi logic điều kiện hay không và khi nào thực hiện. Tùy chọn 'Kế thừa' áp dụng cài đặt cấp khảo sát ('Khi hoàn thành khảo sát' theo mặc định).",
    choicesFromQuestionMode:
      "Chọn từ: 'Tất cả' - sao chép tất cả các tùy chọn lựa chọn từ câu hỏi được chọn; 'Đã chọn' - sao chép động chỉ các tùy chọn lựa chọn đã chọn; 'Chưa chọn' - sao chép động chỉ các tùy chọn lựa chọn chưa chọn. Các tùy chọn 'Không có' và 'Khác' được sao chép theo mặc định nếu được bật trong câu hỏi nguồn.",
    choiceValuesFromQuestion:
      "Trong các loại câu hỏi chọn một và chọn nhiều, mỗi tùy chọn lựa chọn có ID và giá trị hiển thị. Cài đặt này chỉ định cột ma trận hoặc câu hỏi bảng nào sẽ cung cấp ID.",
    choiceTextsFromQuestion:
      "Trong các loại câu hỏi chọn một và chọn nhiều, mỗi tùy chọn lựa chọn có ID và giá trị hiển thị. Cài đặt này chỉ định cột ma trận hoặc câu hỏi bảng nào sẽ cung cấp văn bản hiển thị.",
    allowCustomChoices:
      "Chọn để cho phép người trả lời thêm lựa chọn của riêng họ nếu tùy chọn mong muốn không có trong danh sách thả xuống. Các lựa chọn tùy chỉnh chỉ được lưu trữ tạm thời trong suốt phiên trình duyệt hiện tại.",
    showOtherItem:
      "Khi được chọn, người dùng có thể bao gồm đầu vào bổ sung trong một hộp bình luận riêng.",
    separateSpecialChoices:
      "Hiển thị mỗi tùy chọn lựa chọn đặc biệt ('Không có', 'Khác', 'Chọn tất cả') trên một dòng mới, ngay cả khi sử dụng bố cục đa cột.",
    path: "Chỉ định vị trí trong tập dữ liệu dịch vụ nơi chứa mảng đối tượng mục tiêu. Để trống nếu URL đã trỏ đến mảng.",
    choicesbyurl: {
      valueName:
        "Nhập tên thuộc tính thống nhất trong mảng các đối tượng mà giá trị của nó sẽ được lưu trữ làm câu trả lời trong kết quả khảo sát.",
    },
    titleName:
      "Nhập tên thuộc tính thống nhất trong mảng các đối tượng chứa các giá trị bạn muốn hiển thị trong danh sách lựa chọn.",
    allowEmptyResponse:
      "Chọn để cho phép dịch vụ trả về phản hồi hoặc mảng trống.",
    choicesVisibleIf:
      "Sử dụng biểu tượng đũa phép để đặt quy tắc điều kiện xác định khả năng hiển thị của tất cả các tùy chọn lựa chọn.",
    rateValues:
      "Giá trị bên trái đóng vai trò là ID mục được sử dụng trong các quy tắc điều kiện, giá trị bên phải được hiển thị cho người trả lời.",
    rating: {
      displayMode:
        "'Tự động' chọn giữa các chế độ 'Nút' và 'Danh sách thả xuống' dựa trên chiều rộng có sẵn. Khi chiều rộng không đủ để hiển thị các nút, câu hỏi hiển thị danh sách thả xuống.",
    },
    valuePropertyName:
      "Cho phép bạn kết nối các câu hỏi tạo ra kết quả ở các định dạng khác nhau. Khi các câu hỏi như vậy được liên kết với nhau bằng một định danh kết nối, thuộc tính chia sẻ này lưu trữ các giá trị câu hỏi đã chọn.",
    searchEnabled:
      "Chọn nếu bạn muốn cập nhật nội dung menu thả xuống để phù hợp với truy vấn tìm kiếm mà người dùng đang nhập trong trường nhập.",
    valueTrue:
      "Giá trị được lưu trong kết quả khảo sát khi người trả lời đưa ra câu trả lời tích cực.",
    valueFalse:
      "Giá trị được lưu trong kết quả khảo sát khi người trả lời đưa ra câu trả lời tiêu cực.",
    showPreview:
      "Không khuyến nghị tắt tùy chọn này vì nó ghi đè hình ảnh Xem trước và khiến người dùng khó hiểu liệu các tệp đã được tải lên hay chưa.",
    needConfirmRemoveFile: "Kích hoạt lời nhắc yêu cầu xác nhận xóa tệp.",
    selectToRankEnabled:
      "Bật để xếp hạng chỉ các lựa chọn đã chọn. Người dùng sẽ kéo các mục đã chọn từ danh sách lựa chọn để sắp xếp chúng trong khu vực xếp hạng.",
    dataList:
      "Nhập danh sách các lựa chọn sẽ được gợi ý cho người trả lời trong khi nhập.",
    inputSize:
      "Cài đặt này chỉ thay đổi kích thước các trường nhập và không ảnh hưởng đến chiều rộng của hộp câu hỏi.",
    itemTitleWidth:
      "Đặt chiều rộng nhất quán cho tất cả các nhãn mục. Chấp nhận giá trị CSS (px, %, in, pt, v.v.).",
    inputTextAlignment:
      "Chọn cách căn chỉnh giá trị đầu vào trong trường. Cài đặt mặc định 'Tự động' căn chỉnh giá trị đầu vào sang phải nếu áp dụng mặt nạ tiền tệ hoặc số và sang trái nếu không.",
    altText:
      "Đóng vai trò thay thế khi hình ảnh không thể hiển thị trên thiết bị của người dùng và vì mục đích tiếp cận.",
    rateColorMode:
      "Xác định màu của biểu tượng cảm xúc đã chọn khi loại biểu tượng Đánh giá được đặt thành 'Mặt cười'. Chọn giữa: 'Mặc định' - biểu tượng cảm xúc đã chọn xuất hiện trong màu khảo sát mặc định; 'Thang màu' - biểu tượng cảm xúc đã chọn kế thừa màu từ thang đánh giá.",
    expression: {
      name: "ID biểu thức không hiển thị với người trả lời.",
      description: "Nhập phụ đề biểu thức.",
      expression:
        "Biểu thức có thể bao gồm các phép tính cơ bản (`{q1_id} + {q2_id}`), điều kiện (`{age} > 60`), và các hàm ('iif()`, `today()`, `age()`, `min()`, `max()`, `avg()`, v.v.).",
    },
    storeOthersAsComment:
      "Chọn để lưu trữ giá trị tùy chọn 'Khác' dưới dạng thuộc tính riêng trong kết quả khảo sát.",
    format: "Sử dụng {0} làm trình giữ chỗ cho giá trị thực tế.",
    acceptedTypes:
      "Tham khảo mô tả thuộc tính [accept](https://www.w3schools.com/tags/att_input_accept.asp) để biết thêm thông tin.",
    columnColCount:
      "Sắp xếp các tùy chọn lựa chọn trong bố cục đa cột. Khi đặt thành 0, các tùy chọn được hiển thị trên một dòng. Chỉ áp dụng cho các cột có 'Loại đầu vào ô' được đặt thành Nhóm Nút Radio hoặc Hộp kiểm.",
    autocomplete:
      "Chọn loại dữ liệu mà trình duyệt của người dùng có thể truy xuất. Dữ liệu này được lấy từ các giá trị đã nhập trước đó của người dùng hoặc từ các giá trị được cấu hình sẵn nếu người dùng đã lưu bất kỳ giá trị nào cho tự động hoàn thành.",
    filePlaceholder:
      "Áp dụng khi 'Loại nguồn tệp' là 'Tệp cục bộ' hoặc khi máy ảnh không khả dụng.",
    photoPlaceholder: "Áp dụng khi 'Loại nguồn tệp' là 'Máy ảnh'.",
    fileOrPhotoPlaceholder:
      "Áp dụng khi 'Loại nguồn tệp' là 'Tệp cục bộ hoặc máy ảnh'.",
    colCount:
      "Sắp xếp các tùy chọn lựa chọn trong bố cục đa cột. Khi đặt thành 0, các tùy chọn được hiển thị trên một dòng.",
    masksettings: {
      saveMaskedValue:
        "Chọn nếu bạn muốn lưu trữ giá trị câu hỏi với mặt nạ đã áp dụng trong kết quả khảo sát.",
    },
    patternmask: {
      pattern:
        "Mẫu có thể chứa các ký tự chữ và các trình giữ chỗ sau: `9` - cho chữ số; `a` - cho chữ cái in hoa hoặc thường; `#` - cho chữ số hoặc chữ cái in hoa hoặc thường. Sử dụng dấu gạch chéo ngược `\\` để thoát ký tự.",
    },
    datetimemask: {
      pattern:
        "Mẫu có thể chứa các ký tự phân tách và các trình giữ chỗ sau:<br>`m` - Số tháng.<br>`mm` - Số tháng, có số 0 đứng đầu cho các giá trị một chữ số.<br>`d` - Ngày trong tháng.<br>`dd` - Ngày trong tháng, có số 0 đứng đầu cho các giá trị một chữ số.<br>`yy` - Hai chữ số cuối của năm.<br>`yyyy` - Năm bốn chữ số.<br>`H` - Giờ ở định dạng 24 giờ.<br>`HH` - Giờ ở định dạng 24 giờ, có số 0 đứng đầu cho các giá trị một chữ số.<br>`h` - Giờ ở định dạng 12 giờ.<br>`hh` - Giờ ở định dạng 12 giờ, có số 0 đứng đầu cho các giá trị một chữ số.<br>`MM` - Phút.<br>`ss` - Giây.<br>`TT` - Chu kỳ đồng hồ 12 giờ ở chữ in hoa (AM/PM).<br>`tt` - Chu kỳ đồng hồ 12 giờ ở chữ thường (am/pm).",
    },
    numericmask: {
      decimalSeparator:
        "Ký hiệu được sử dụng để tách phần thập phân khỏi phần nguyên của số hiển thị.",
      thousandsSeparator:
        "Ký hiệu được sử dụng để tách các chữ số của số lớn thành các nhóm ba chữ số.",
      precision:
        "Giới hạn số chữ số cần giữ sau dấu thập phân cho số hiển thị.",
    },
    currencymask: {
      prefix: "Một hoặc nhiều ký hiệu được hiển thị trước giá trị.",
      suffix: "Một hoặc nhiều ký hiệu được hiển thị sau giá trị.",
    },
    theme: {
      isPanelless: "Cài đặt này chỉ áp dụng cho các câu hỏi bên ngoài bảng.",
      primaryColor: "Đặt màu bổ sung làm nổi bật các phần tử khảo sát chính.",
      panelBackgroundTransparency:
        "Điều chỉnh độ trong suốt của bảng và hộp câu hỏi so với nền khảo sát.",
      questionBackgroundTransparency:
        "Điều chỉnh độ trong suốt của các phần tử nhập so với nền khảo sát.",
      cornerRadius:
        "Đặt bán kính góc cho tất cả các phần tử hình chữ nhật. Bật Chế độ Nâng cao nếu bạn muốn đặt các giá trị bán kính góc riêng lẻ cho các phần tử nhập hoặc bảng và hộp câu hỏi.",
      "--sjs-general-backcolor-dim": "Đặt màu nền chính của khảo sát.",
    },
    header: {
      inheritWidthFrom:
        "Tùy chọn 'Giống bộ chứa' tự động điều chỉnh chiều rộng khu vực nội dung tiêu đề để vừa với phần tử HTML mà khảo sát được đặt vào.",
      textAreaWidth:
        "Chiều rộng của khu vực tiêu đề chứa tiêu đề và mô tả khảo sát, được đo bằng pixel.",
      overlapEnabled:
        "Khi được bật, phần đầu của khảo sát sẽ chồng lên phần dưới của tiêu đề.",
      mobileHeight:
        "Khi đặt thành 0, chiều cao được tính toán tự động để phù hợp với nội dung của tiêu đề.",
    },
    progressBarInheritWidthFrom:
      "Tùy chọn 'Giống bộ chứa' tự động điều chỉnh chiều rộng khu vực thanh tiến trình để vừa với phần tử HTML mà khảo sát được đặt vào.",
    singleInputTitleTemplate:
      "Được sử dụng khi 'Bố cục khảo sát' được đặt thành 'Một trường nhập trên mỗi trang'. Trong bố cục này, ma trận được chia để mỗi trường nhập xuất hiện trên một trang riêng. Sử dụng trình giữ chỗ {rowIndex} để chèn số tự động, {rowTitle} hoặc {rowName} để tham chiếu tiêu đề hoặc ID của dòng, và {row.columnid} để bao gồm giá trị của một cột ma trận cụ thể.",
  },

  p: {
    title: {
      name: "tiêu đề",
      title: "Để trống nếu giống với 'Tên'",
    },
    multiSelect: "Cho phép chọn nhiều",
    showLabel: "Hiển thị chú thích hình ảnh và video",
    swapOrder: "Hoán đổi thứ tự Có và Không",
    value: "Giá trị",
    tabAlign: "Căn chỉnh tab",
    sourceType: "Loại nguồn tệp",
    fitToContainer: "Vừa với bộ chứa",
    setValueExpression: "Biểu thức đặt giá trị",
    description: "Mô tả",
    logoFit: "Cách hiển thị logo",
    pages: "Trang",
    questions: "Câu hỏi",
    triggers: "Trình kích hoạt",
    calculatedValues: "Biến tùy chỉnh",
    surveyId: "ID khảo sát",
    surveyPostId: "ID bài đăng khảo sát",
    surveyShowDataSaving: "Hiển thị lưu dữ liệu khảo sát",
    questionDescriptionLocation: "Căn chỉnh mô tả câu hỏi",
    progressBarType: "Loại thanh tiến trình",
    showTOC: "Hiển thị mục lục (TOC)",
    tocLocation: "Căn chỉnh mục lục",
    questionTitlePattern: "Mẫu tiêu đề câu hỏi",
    widthMode: "Chế độ chiều rộng khảo sát",
    showBrandInfo: "Hiển thị thông tin thương hiệu",
    useDisplayValuesInDynamicTexts:
      "Sử dụng giá trị hiển thị trong văn bản động",
    visibleIf: "Hiển thị nếu",
    defaultValueExpression: "Biểu thức giá trị mặc định",
    requiredIf: "Bắt buộc nếu",
    resetValueIf: "Đặt lại giá trị nếu",
    setValueIf: "Đặt giá trị nếu",
    validators: "Quy tắc xác thực",
    bindings: "Ràng buộc",
    renderAs: "Hiển thị dưới dạng",
    attachOriginalItems: "Đính kèm các mục gốc",
    choices: "Lựa chọn",
    choicesByUrl: "Lựa chọn theo URL",
    currency: "Tiền tệ",
    cellHint: "Gợi ý ô",
    totalMaximumFractionDigits: "Số chữ số thập phân tối đa tổng",
    totalMinimumFractionDigits: "Số chữ số thập phân tối thiểu tổng",
    columns: "Cột",
    detailElements: "Phần tử chi tiết",
    allowAdaptiveActions: "Cho phép hành động thích ứng",
    defaultRowValue: "Giá trị dòng mặc định",
    detailPanelShowOnAdding: "Hiển thị bảng chi tiết khi thêm",
    choicesLazyLoadEnabled: "Bật tải lười lựa chọn",
    choicesLazyLoadPageSize: "Kích thước trang tải lười lựa chọn",
    inputFieldComponent: "Thành phần trường nhập",
    itemComponent: "Thành phần mục",
    min: "Tối thiểu",
    max: "Tối đa",
    minValueExpression: "Biểu thức giá trị tối thiểu",
    maxValueExpression: "Biểu thức giá trị tối đa",
    step: "Bước",
    dataList: "Mục gợi ý tự động",
    inputSize: "Chiều rộng trường nhập (theo ký tự)",
    itemTitleWidth: "Chiều rộng nhãn mục",
    inputTextAlignment: "Căn chỉnh giá trị nhập",
    elements: "Phần tử",
    content: "Nội dung",
    navigationTitle: "Tiêu đề điều hướng",
    navigationDescription: "Mô tả điều hướng",
    longTap: "Chạm lâu",
    autoGrow: "Mở rộng trường nhập động",
    allowResize: "Bật tay cầm thay đổi kích thước",
    acceptCarriageReturn: "Chấp nhận ký tự xuống dòng",
    displayMode: "Chế độ hiển thị",
    rateType: "Loại đánh giá",
    label: "Nhãn",
    contentMode: "Chế độ nội dung",
    imageFit: "Cách hiển thị hình ảnh và hình thu nhỏ",
    altText: "Văn bản thay thế",
    height: "Chiều cao",
    mobileHeight: "Chiều cao trên điện thoại thông minh",
    penColor: "Màu bút",
    backgroundColor: "Màu nền",
    templateElements: "Phần tử mẫu",
    operator: "Toán tử",
    isVariable: "Là biến",
    runExpression: "Chạy biểu thức",
    showCaption: "Hiển thị chú thích",
    iconName: "Tên biểu tượng",
    iconSize: "Kích thước biểu tượng",
    precision: "Độ chính xác",
    matrixDragHandleArea: "Khu vực tay cầm kéo ma trận",
    backgroundImage: "Hình nền",
    backgroundImageFit: "Cách hiển thị hình nền",
    backgroundImageAttachment: "Đính kèm hình nền",
    backgroundOpacity: "Độ trong suốt nền",
    selectToRankEnabled: "Cho phép xếp hạng chọn lọc",
    selectToRankAreasLayout: "Căn chỉnh khu vực xếp hạng",
    selectToRankEmptyRankedAreaText:
      "Văn bản hiển thị nếu tất cả tùy chọn được chọn",
    selectToRankEmptyUnrankedAreaText:
      "Văn bản trình giữ chỗ cho khu vực xếp hạng",
    allowCameraAccess: "Cho phép truy cập máy ảnh",
    scaleColorMode: "Chế độ màu biểu tượng đánh giá",
    rateColorMode: "Sơ đồ màu mặt cười",
    copyDisplayValue: "Sao chép giá trị hiển thị",
    effectiveColSpan: "Khoảng cột",
    progressBarInheritWidthFrom: "Chiều rộng khu vực thanh tiến trình",
  },
  theme: {
    advancedMode: "Chế độ nâng cao",
    pageTitle: "Trang",
    questionTitle: "Hộp câu hỏi",
    editorPanel: "Phần tử nhập",
    lines: "Dòng",
    primaryDefaultColor: "Mặc định",
    primaryDarkColor: "Khi di chuột",
    primaryLightColor: "Đã chọn",
    backgroundDimColor: "Màu nền",
    cornerRadius: "Bán kính góc",
    backcolor: "Nền mặc định",
    hovercolor: "Nền khi di chuột",
    borderDecoration: "Trang trí viền",
    fontColor: "Màu phông chữ",
    backgroundColor: "Màu nền",
    primaryForecolor: "Màu mặc định",
    primaryForecolorLight: "Màu tắt",
    font: "Phông chữ",
    borderDefault: "Tối hơn",
    borderLight: "Sáng hơn",
    fontFamily: "Gia đình phông chữ",
    fontWeightRegular: "Bình thường",
    fontWeightHeavy: "Nặng",
    fontWeightSemiBold: "Bán đậm",
    fontWeightBold: "Đậm",
    color: "Màu sắc",
    placeholderColor: "Màu trình giữ chỗ",
    size: "Kích thước",
    opacity: "Độ trong suốt",
    boxShadowX: "X",
    boxShadowY: "Y",
    boxShadowAddRule: "Thêm hiệu ứng bóng",
    boxShadowBlur: "Làm mờ",
    boxShadowSpread: "Lan tỏa",
    boxShadowDrop: "Thả",
    boxShadowInner: "Bên trong",
    names: {
      default: "Mặc định",
      sharp: "Sắc nét",
      borderless: "Không viền",
      flat: "Phẳng",
      plain: "Đơn giản",
      doubleborder: "Viền đôi",
      layered: "Phân lớp",
      solid: "Rắn",
      threedimensional: "3D",
      contrast: "Tương phản",
    },
    colors: {
      teal: "Xanh lam",
      blue: "Xanh dương",
      purple: "Tím",
      orchid: "Lan",
      tulip: "Tulip",
      brown: "Nâu",
      green: "Xanh lá",
      gray: "Xám",
    },
  },
  creatortheme: {
    "--sjs-special-background": "Nền bề mặt",
    "--sjs-primary-background-500": "Chính",
    "--sjs-secondary-background-500": "Phụ",
    surfaceScale: "Bề mặt",
    userInterfaceBaseUnit: "Phần tử giao diện người dùng",
    fontScale: "Phông chữ",
    names: {
      sc2020: "Survey Creator 2020",
      "default-light": "Sáng",
      "default-dark": "Tối",
      "default-contrast": "Tương phản",
    },
  },
};
